#!/usr/bin/env python3

import json
from datetime import datetime, timezone
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[2]
OUTPUT_DIR = REPO_ROOT / ".repo_context" / "generated"

SECTIONS = [
    {"name": "core_source", "path": "src/datasystem", "max_depth": 2},
    {"name": "public_headers", "path": "include/datasystem", "max_depth": 2},
    {"name": "python_sdk", "path": "python/yr/datasystem", "max_depth": 1},
    {"name": "cli", "path": "cli", "max_depth": 2},
    {"name": "tests", "path": "tests", "max_depth": 2},
    {"name": "examples", "path": "example", "max_depth": 2},
    {"name": "docs", "path": "docs/source_zh_cn", "max_depth": 2},
    {"name": "skills", "path": ".skills", "max_depth": 3},
    {"name": "transfer_engine", "path": "transfer_engine", "max_depth": 2},
]

ROOT_FILES = [
    "README.md",
    "build.sh",
    "CMakeLists.txt",
    "WORKSPACE",
    ".bazelrc",
    "requirements.txt",
]

IGNORED_NAMES = {
    "__pycache__",
    ".DS_Store",
}


def tree_lines(root: Path, max_depth: int) -> list[str]:
    if not root.exists():
        return []

    lines: list[str] = []
    base_depth = len(root.parts)

    def walk(current: Path) -> None:
        rel_depth = len(current.parts) - base_depth
        if rel_depth > max_depth:
            return
        if rel_depth > 0:
            indent = "  " * (rel_depth - 1)
            suffix = "/" if current.is_dir() else ""
            lines.append(f"{indent}- {current.name}{suffix}")
        if current.is_dir() and rel_depth < max_depth:
            for child in sorted(current.iterdir(), key=lambda item: (not item.is_dir(), item.name)):
                if child.name.startswith(".") or child.name in IGNORED_NAMES:
                    continue
                walk(child)

    walk(root)
    return lines


def build_payload() -> dict:
    generated_at = datetime.now(timezone.utc).replace(microsecond=0).isoformat()
    payload = {
        "repo_root": str(REPO_ROOT),
        "generated_at_utc": generated_at,
        "root_files": [name for name in ROOT_FILES if (REPO_ROOT / name).exists()],
        "sections": [],
    }

    for section in SECTIONS:
        path = REPO_ROOT / section["path"]
        payload["sections"].append(
            {
                "name": section["name"],
                "path": section["path"],
                "exists": path.exists(),
                "tree": tree_lines(path, section["max_depth"]),
            }
        )
    return payload


def to_markdown(payload: dict) -> str:
    lines = [
        "# Generated Repository Index",
        "",
        "This file is generated by `python3 scripts/ai_context/generate_repo_index.py`.",
        "",
        f"- Repository root: `{payload['repo_root']}`",
        f"- Generated at (UTC): `{payload['generated_at_utc']}`",
        "",
        "## Root Files",
        "",
    ]

    for root_file in payload["root_files"]:
        lines.append(f"- `{root_file}`")

    for section in payload["sections"]:
        lines.extend(
            [
                "",
                f"## {section['name']}",
                "",
                f"- Path: `{section['path']}`",
                f"- Exists: `{section['exists']}`",
                "",
            ]
        )
        if section["tree"]:
            lines.append("```text")
            lines.append(section["path"] + "/")
            lines.extend(section["tree"])
            lines.append("```")
        else:
            lines.append("_No entries collected._")

    lines.append("")
    lines.append("## Regeneration")
    lines.append("")
    lines.append("```bash")
    lines.append("python3 scripts/ai_context/generate_repo_index.py")
    lines.append("```")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    payload = build_payload()
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    json_path = OUTPUT_DIR / "repo_index.json"
    md_path = OUTPUT_DIR / "repo_index.md"

    json_path.write_text(json.dumps(payload, indent=2, ensure_ascii=True) + "\n", encoding="utf-8")
    md_path.write_text(to_markdown(payload), encoding="utf-8")


if __name__ == "__main__":
    main()
