load("//bazel:build_defs.bzl", "ds_cc_test")

package(default_visibility = ["//visibility:public"])

ds_cc_test(
    name = "hixl_rh2d_smoke_test",
    srcs = ["hixl_rh2d_smoke_test.cpp"],
    linkopts = [
        "-lrt",
    ],
    tags = [
        "hixl",
        "manual",
        "requires-npu",
    ],
    deps = [
        "//src/datasystem/common/log:common_log",
        "@local_ascend//:hixl",
    ],
)

ds_cc_test(
    name = "roce_transport_test",
    srcs = ["roce_transport_test.cpp"],
    tags = ["npu"],
    deps = [
        "//src/datasystem/common/rdma/npu:remote_h2d_manager",
        "@com_google_googletest//:gtest",
    ],
)
