load("//bazel:build_defs.bzl", "ds_cc_test")

package(default_visibility = ["//visibility:public"])

ds_cc_test(
    name = "ub_health_lease_sync_test",
    srcs = ["ub_health_lease_sync_test.cpp"],
    deps = [
        "//src/datasystem/cluster:cluster_topology",
        "//src/datasystem/cluster/coordination_backend:coordination_backend",
        "//src/datasystem/common/object_cache:common_object_cache",
        "//src/datasystem/protos:share_memory_cc_proto",
        "//tests/ut/cluster/testing:fake_coordination_backend",
        "//tests/ut:ut_common",
    ],
)

ds_cc_test(
    name = "ds_coordination_backend_session_test",
    srcs = ["ds_coordination_backend_session_test.cpp"],
    deps = [
        "//src/datasystem/cluster/coordination_backend:coordination_backend",
        "//tests/ut:ut_common",
    ],
)

ds_cc_test(
    name = "topology_controller_test",
    srcs = ["topology_controller_test.cpp"],
    timeout = "short",
    deps = [
        "//src/datasystem/cluster:cluster_topology",
        "//src/datasystem/protos:coordinator_cc_proto",
        "//tests/ut/cluster/testing:fake_coordination_backend",
        "//tests/ut:ut_common",
    ],
)

ds_cc_test(
    name = "topology_engine_test",
    srcs = ["topology_engine_test.cpp"],
    deps = [
        "//src/datasystem/cluster:cluster_topology",
        "//src/datasystem/common/flags:dynamic_flag_config",
        "//tests/ut/cluster/testing:fake_coordinator_service_proxy",
        "//tests/ut:ut_common",
    ],
)

test_suite(
    name = "all_cluster_tests",
    tests = [
        "ds_coordination_backend_session_test",
        "topology_controller_test",
        "topology_engine_test",
        "ub_health_lease_sync_test",
    ],
)
