/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Description: Applies topology change plans to repository facts.
 */
#ifndef DATASYSTEM_TOPOLOGY_ORCHESTRATION_TOPOLOGY_MUTATION_APPLIER_H
#define DATASYSTEM_TOPOLOGY_ORCHESTRATION_TOPOLOGY_MUTATION_APPLIER_H

#include <vector>

#include "datasystem/topology/repository/topology_repository.h"

namespace datasystem {
namespace topology {

class TopologyMutationApplier final {
public:
    explicit TopologyMutationApplier(ITopologyControllerRepository &repository);
    ~TopologyMutationApplier() = default;

    /**
     * @brief Persist one topology change plan.
     * @param[in] plan Plan generated by TopologyPlanBuilder.
     * @param[out] result Mutation result counters and final revision.
     * @return K_OK on success; repository errors otherwise.
     */
    Status Apply(const TopologyChangePlan &plan, TopologyReconcileResult &result);

private:
    Status CreateTasks(const TopologyChangePlan &plan, TopologyReconcileResult &result,
                       std::vector<TaskId> &createdTransferTasks, std::vector<TaskId> &createdRecoveryTasks);
    Status WriteNotifies(const TopologyChangePlan &plan, TopologyReconcileResult &result);
    void RollbackCreatedTasks(const std::vector<TaskId> &createdTransferTasks,
                              const std::vector<TaskId> &createdRecoveryTasks);

    ITopologyControllerRepository &repository_;
};

}  // namespace topology
}  // namespace datasystem
#endif  // DATASYSTEM_TOPOLOGY_ORCHESTRATION_TOPOLOGY_MUTATION_APPLIER_H
