# tests/ut/BUILD.bazel
"""DataSystem 单元测试公共配置"""

load("//bazel:build_defs.bzl", "ds_cc_test_library")

package(default_visibility = ["//visibility:public"])

ds_cc_test_library(
    name = "ut_common_headers",
    hdrs = ["common.h"],
    deps = [
        "//src/datasystem/common/log:common_log",
        "//src/datasystem/common/util:status_helper",
    ],
)

# 单元测试公共库
ds_cc_test_library(
    name = "ut_common",
    srcs = ["common.cpp"],
    hdrs = [
        "bench_helper.h",
    ],
    defines = [
        "LLT_BIN_PATH=\"$(GENDIR)/tests/ut\"",
    ],
    deps = [
        ":ut_common_headers",
        "//src/datasystem/common/log:common_log",
        "//src/datasystem/common/rdma:fast_transport_manager_wrapper",
        "//src/datasystem/common/rdma:rdma_util",
        "//src/datasystem/common/util:file_util",
        "//src/datasystem/common/util:uuid_generator",
        "@securec",
    ],
)

ds_cc_test_library(
    name = "bthread_test_helper",
    hdrs = ["bthread_test_helper.h"],
    deps = ["//src/datasystem/common/rpc:bthread_utils"],
)
