load("//:version.bzl", "DATASYSTEM_VERSION")
load("//bazel:build_defs.bzl", "ds_cc_library")

package(default_visibility = ["//visibility:public"])

ds_cc_library(
    name = "transport_exist_types",
    hdrs = [
        "rpc/exist_types.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//include/datasystem/utils:utils_headers",
    ],
)

ds_cc_library(
    name = "transport_phase_latency_recorder",
    srcs = ["transport_phase_latency_recorder.cpp"],
    hdrs = ["transport_phase_latency_recorder.h"],
    visibility = ["//visibility:public"],
    deps = [
        "//src/datasystem/common/log:common_log",
        "//src/datasystem/common/util:net_util",
    ],
)

ds_cc_library(
    name = "client_transport",
    srcs = [
        "transport_advisor.cpp",
        "common/deadline_retry.cpp",
        "metadata/object_metadata_client.cpp",
        "object_read/object_read_flow.cpp",
        "object_read/replica_reader.cpp",
        "transport_layer.cpp",
        "worker_snapshot.cpp",
        "data_plane/data_plane_executor.cpp",
        "data_plane/data_plane_manager.cpp",
        "data_plane/shm_connection.cpp",
        "data_plane/shm_receive_buffer_owner.cpp",
        "data_plane/shm_send_buffer_owner.cpp",
        "data_plane/tcp_transporter.cpp",
        "data_plane/ub_connection.cpp",
        "data_plane/ub_transporter.cpp",
        "rpc/exist_request_builder.cpp",
        "rpc/mset_request_builder.cpp",
        "rpc/set_request_builder.cpp",
        "rpc/worker_rpc_client.cpp",
    ],
    defines = [
        "DATASYSTEM_VERSION=\\\"{}\\\"".format(DATASYSTEM_VERSION),
    ],
    hdrs = [
        "object_buffer_internal.h",
        "transport_advisor.h",
        "shm_fd.h",
        "transport_kind.h",
        "transport_layer.h",
        "worker_snapshot.h",
        "common/deadline_retry.h",
        "metadata/object_metadata_client.h",
        "object_read/object_read_flow.h",
        "object_read/object_read_types.h",
        "object_read/replica_reader.h",
        "data_plane/data_plane_executor.h",
        "data_plane/data_plane_manager.h",
        "data_plane/i_data_plane_connection.h",
        "data_plane/i_data_transporter.h",
        "data_plane/shm_connection.h",
        "data_plane/shm_receive_buffer_owner.h",
        "data_plane/shm_send_buffer_owner.h",
        "data_plane/shm_transporter.h",
        "data_plane/tcp_transporter.h",
        "data_plane/ub_connection.h",
        "data_plane/ub_transporter.h",
        "rpc/exist_request_builder.h",
        "rpc/exist_types.h",
        "rpc/mset_request_builder.h",
        "rpc/set_request_builder.h",
        "rpc/worker_rpc_client.h",
    ],
    visibility = ["//visibility:public"],
    deps = [
        ":transport_exist_types",
        ":transport_phase_latency_recorder",
        "//include/datasystem:headers",
        "//src/datasystem/client/worker_api:client_worker_common_api",
        "//src/datasystem/client/mmap_manager:mmap_manager",
        "//src/datasystem/client/object_cache/routing:routing",
        "//src/datasystem/common/ak_sk:signature",
        "//src/datasystem/common/eventloop:common_event_loop",
        "//src/datasystem/common/flags:dynamic_flag_config",
        "//src/datasystem/common/inject:common_inject",
        "//src/datasystem/common/log:access_recorder_header",
        "//src/datasystem/common/metrics:common_metrics",
        "//src/datasystem/common/object_cache:object_base",
        "//src/datasystem/common/object_cache:object_buffer",
        "//src/datasystem/common/perf:common_perf",
        "//src/datasystem/common/rdma:common_rdma",
        "//src/datasystem/common/log:common_log",
        "//src/datasystem/common/rpc:api_deadline",
        "//src/datasystem/common/rpc:api_deadline_helpers",
        "//src/datasystem/common/rpc:brpc_factory",
        "//src/datasystem/common/rpc:mem_view",
        "//src/datasystem/common/rpc:rpc_message",
        "//src/datasystem/common/rpc:rpc_options",
        "//src/datasystem/common/rpc:timeout_duration",
        "//src/datasystem/common/rpc:unix_sock_fd",
        "//src/datasystem/common/shared_memory:common_shm_unit_info",
        "//src/datasystem/common/util:common_util",
        "//src/datasystem/common/util:numa_util",
        "//src/datasystem/common/util:rpc_diagnostic",
        "//src/datasystem/common/util:rpc_util",
        "//src/datasystem/common/util:thread_pool",
        "//src/datasystem/common/util:validator",
        "//src/datasystem/protos:object_posix_brpc",
        "//src/datasystem/protos:master_object_brpc",
        "//src/datasystem/protos:share_memory_brpc",
        "//src/datasystem/protos:cluster_topology_cc_proto",
        "//src/datasystem/protos:worker_object_brpc",
        "@com_github_apache_brpc//:brpc",
        "@tbb//:tbb",
    ],
    alwayslink = True,
)
