load("//bazel:build_defs.bzl", "ds_cc_test")

package(default_visibility = ["//visibility:public"])

ds_cc_test(
    name = "coordinator_store_backend_test",
    srcs = ["coordinator_store_backend_test.cpp"],
    deps = [
        "//src/datasystem/common/coordinator:coordinator_store",
        "//src/datasystem/coordinator:coordinator_store_backend",
        "//tests/ut:ut_common",
    ],
)

ds_cc_test(
    name = "topology_control_host_test",
    srcs = ["topology_control_host_test.cpp"],
    deps = [
        "//src/datasystem/cluster:cluster_topology",
        "//src/datasystem/common/coordinator:coordinator_store",
        "//src/datasystem/coordinator:coordinator_topology_control_host",
        "//src/datasystem/coordinator:coordinator_topology_recovery_manager",
        "//tests/ut:ut_common",
    ],
)

ds_cc_test(
    name = "topology_control_perf_test",
    srcs = ["topology_control_perf_test.cpp"],
    tags = ["manual"],
    deps = [
        "//src/datasystem/cluster:cluster_topology",
        "//tests/ut:ut_common",
    ],
)

ds_cc_test(
    name = "coordinator_server_options_test",
    srcs = ["coordinator_server_options_test.cpp"],
    timeout = "short",
    deps = [
        "//include/datasystem/utils:utils_headers",
        "//src/datasystem/common/flags:dynamic_flag_config",
        "//src/datasystem/common/flags:dynamic_flag_config_header",
        "//src/datasystem/common/rpc:brpc_factory",
        "//src/datasystem/common/signal:signal",
        "//src/datasystem/coordinator:coordinator_server",
        "//src/datasystem/coordinator:coordinator_runtime",
        "//src/datasystem/coordinator:coordinator_service_impl",
        "//src/datasystem/coordinator/raft:coordinator_election_manager",
        "//src/datasystem/protos:coordinator_brpc",
        "//tests/st/cluster:test_port_allocator",
        "//tests/ut:ut_common",
    ],
)
