set -euo pipefail
CMAKE_INSTALL_ROOT="/tmp/b9c150afb2835b37f77c6baa76040cdfb901bd65351a00994eaa576de589a4ed"
PROJECT_ROOT="$(cd "$(dirname "$0")/.." && pwd)"
OUTPUT_DIR="$PROJECT_ROOT/cmake-prebuilt"

mkdir -p "$OUTPUT_DIR"

cat > "$OUTPUT_DIR/BUILD.bazel" <<'EOF'
# Generated by scripts/generate-cmake-prebuilt.sh
# DO NOT EDIT MANUALLY

load("@rules_cc//cc:defs.bzl", "cc_import", "cc_library")

package(default_visibility = ["//visibility:public"])
EOF

for dir in "$CMAKE_INSTALL_ROOT"/*; do
  [ -d "$dir" ] || continue
  dirname=$(basename "$dir")
  libname="${dirname%_*}"
  link_target="$OUTPUT_DIR/$libname"
  [ -e "$link_target" ] && rm -rf "$link_target"
  ln -s "$dir" "$link_target"

  if [ ! -d "$dir/lib" ]; then
    echo "" >> "$OUTPUT_DIR/BUILD.bazel"
    echo "cc_library(" >> "$OUTPUT_DIR/BUILD.bazel"
    echo "    name = \"$libname\"," >> "$OUTPUT_DIR/BUILD.bazel"
    echo "    hdrs = glob([\"$libname/include/**/*.h\"])," >> "$OUTPUT_DIR/BUILD.bazel"
    echo "    includes = [\"$libname/include\"]," >> "$OUTPUT_DIR/BUILD.bazel"
    echo ")" >> "$OUTPUT_DIR/BUILD.bazel"
    continue
  fi
  
  libs=$(find "$dir/lib" -type f \( -name '*.a' -o -name '*.so' \) -printf '%f\n' | sed 's/^lib//' | sed 's/\.\(a\|so\)$//' | sort -u)
  if [ -z "$libs" ]; then
    echo "WARN: $libname has no library files, skip"
    continue
  fi

  for l in $libs; do
    static="$link_target/lib/lib$l.a"
    shared="$link_target/lib/lib$l.so"
    import_name="${libname}-${l}-lib"
    echo "" >> "$OUTPUT_DIR/BUILD.bazel"
    echo "cc_import(" >> "$OUTPUT_DIR/BUILD.bazel"
    echo "    name = \"$import_name\"," >> "$OUTPUT_DIR/BUILD.bazel"
    [ -f "$static" ] && echo "    static_library = \"$libname/lib/lib$l.a\"," >> "$OUTPUT_DIR/BUILD.bazel"
    [ -f "$shared" ] && echo "    shared_library = \"$libname/lib/lib$l.so\"," >> "$OUTPUT_DIR/BUILD.bazel"
    echo ")" >> "$OUTPUT_DIR/BUILD.bazel"
  done

  echo "" >> "$OUTPUT_DIR/BUILD.bazel"
  echo "cc_library(" >> "$OUTPUT_DIR/BUILD.bazel"
  echo "    name = \"$libname\"," >> "$OUTPUT_DIR/BUILD.bazel"
  echo "    hdrs = glob([\"$libname/include/**/*.h\"])," >> "$OUTPUT_DIR/BUILD.bazel"
  echo "    includes = [\"$libname/include\"]," >> "$OUTPUT_DIR/BUILD.bazel"
  echo "    deps = [" >> "$OUTPUT_DIR/BUILD.bazel"
  for l in $libs; do
    echo "        \":${libname}-${l}-lib\"," >> "$OUTPUT_DIR/BUILD.bazel"
  done
  echo "    ]," >> "$OUTPUT_DIR/BUILD.bazel"
  echo ")" >> "$OUTPUT_DIR/BUILD.bazel"
done

echo "Done. Now you can use //cmake-prebuilt:<lib> in any BUILD file."