find_package(Cuda)
include(${CMAKE_SOURCE_DIR}/cmake/external_libs/mlcachedirect.cmake)
if(NOT CUDA_INCLUDE_DIR)
    message(WARNING "CUDA_INCLUDE_DIR is empty. Enabling PIPLN_USE_MOCK globally.")
    add_compile_definitions(PIPLN_USE_MOCK)
endif()
