/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2022. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Description: Brpc adapter generator (V8 three-output pattern).
 * Generates {ServiceName}BrpcAdapter classes that wrap I{ServiceName} and
 * implement brpc::Service for brpc integration.
 */
#include "datasystem/common/rpc/plugin_generator/rpc_generator.h"

#include <google/protobuf/descriptor.h>

namespace datasystem {

// --- Brpc adapter header ---

void RpcGenerator::CreateBrpcAdapterHeader(const google::protobuf::FileDescriptor &file,
                                           compiler::GeneratorContext *generatorCtx) const
{
    std::unique_ptr<io::ZeroCopyOutputStream> outputFile(generatorCtx->Open(fileName + ".brpc.pb.h"));
    io::Printer printer(outputFile.get(), '$');

    GenerateBrpcAdapterPrologue(printer, file);
    printer.PrintRaw(namespaceBegin);

    for (auto i = 0; i < file.service_count(); ++i) {
        auto *svc = file.service(i);
        GenerateBrpcAdapter(printer, *svc, PREFIX);
    }

    printer.PrintRaw(namespaceEnd);
    printer.PrintRaw(ENDIF);
}

void RpcGenerator::GenerateBrpcAdapterPrologue(io::Printer &printer,
                                               const google::protobuf::FileDescriptor &file) const
{
    std::map<std::string, std::string> vars;
    vars["full_file_name"] = file.name();
    vars["file_name"] = fileName;
    std::string fileNameHeader = fileName;
    std::replace(fileNameHeader.begin(), fileNameHeader.end(), '/', '_');
    vars["file_name_header"] = fileNameHeader;
    std::string impl =
        "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
        "// source: $full_file_name$\n"
        "#ifndef DATASYSTEM_PROTO_BRPC_$file_name_header$_ADAPTER_H\n"
        "#define DATASYSTEM_PROTO_BRPC_$file_name_header$_ADAPTER_H\n"
        "#include <memory>\n"
        "#include <vector>\n";
    if (file.message_type_count() > 0) {
        impl += "#include \"$file_name$.pb.h\"\n";
    }
    impl +=
        "#include \"$file_name$.irpc.pb.h\"\n"
        "#include <google/protobuf/service.h>\n"
        "#include <brpc/controller.h>\n"
        "#include <brpc/stream.h>\n"
        "#include \"datasystem/common/rpc/brpc_server_unary_writer_reader.h\"\n"
        "#include \"datasystem/common/rpc/brpc_server_writer_reader_impl.h\"\n"
        "#include \"datasystem/common/rpc/brpc_server_stream_impl.h\"\n"
        "#include \"datasystem/common/rpc/rpc_message.h\"\n"
        "#include \"datasystem/utils/status.h\"\n";
    printer.Print(vars, impl.c_str());
    for (auto k = 0; k < file.dependency_count(); ++k) {
        auto depend = file.dependency(k)->name();
        bool isAProto = StripSuffix(depend, ".proto");
        if (isAProto) {
            vars["depend"] = depend;
            printer.Print(vars, "#include \"$depend$.pb.h\"\n");
        }
    }
    printer.PrintRaw("#include <string>\n");
}

void RpcGenerator::GenerateBrpcAdapter(io::Printer &printer, const google::protobuf::ServiceDescriptor &svc,
                                       const std::string &indent) const
{
    (void)indent;
    const std::string &svcName = svc.name();
    std::map<std::string, std::string> vars;
    vars["svc_name"] = svcName;
    vars["interface_name"] = "I" + svcName;
    vars["adapter_name"] = svcName + "BrpcAdapter";

    // Build method descriptor entries for GetDescriptor/GetRequestPrototype/GetResponsePrototype
    std::string methodDescriptors;
    for (int i = 0; i < svc.method_count(); ++i) {
        const auto *method = svc.method(i);
        vars["method_name"] = method->name();
        vars["req_name"] = method->input_type()->name();
        vars["rsp_name"] = method->output_type()->name();
        vars["idx"] = std::to_string(i);
        methodDescriptors +=
            "    static const google::protobuf::MethodDescriptor* method_descriptor_$idx$;\n"
            "    static const $req_name$& request_prototype_$idx$;\n"
            "    static const $rsp_name$& response_prototype_$idx$;\n";
    }

    std::string impl =
        "class $adapter_name$ : public google::protobuf::Service {\n"
        "public:\n"
        "    typedef $interface_name$ Interface;\n"
        "    explicit $adapter_name$($interface_name$ &impl) : impl_(impl) {}\n"
        "    ~$adapter_name$() override = default;\n"
        "    const google::protobuf::ServiceDescriptor* GetDescriptor() override;\n"
        "    const google::protobuf::Message& GetRequestPrototype(\n"
        "        const google::protobuf::MethodDescriptor* method) const override;\n"
        "    const google::protobuf::Message& GetResponsePrototype(\n"
        "        const google::protobuf::MethodDescriptor* method) const override;\n"
        "    void CallMethod(const google::protobuf::MethodDescriptor* method,\n"
        "                    google::protobuf::RpcController* cntl_base,\n"
        "                    const google::protobuf::Message* request,\n"
        "                    google::protobuf::Message* response,\n"
        "                    google::protobuf::Closure* done) override;\n"
        "    ::datasystem::Status DirectCallMethod(const google::protobuf::MethodDescriptor* method,\n"
        "                                          google::protobuf::RpcController* cntl_base,\n"
        "                                          const google::protobuf::Message* request,\n"
        "                                          google::protobuf::Message* response,\n"
        "                                          google::protobuf::Closure* done);\n"
        "private:\n"
        "    $interface_name$ &impl_;\n"
        "};\n";
    printer.Print(vars, impl.c_str());
}

// --- Brpc adapter cpp ---

void RpcGenerator::CreateBrpcAdapterCpp(const google::protobuf::FileDescriptor &file,
                                        compiler::GeneratorContext *generatorCtx) const
{
    std::unique_ptr<io::ZeroCopyOutputStream> outputFile(generatorCtx->Open(fileName + ".brpc.pb.cc"));
    io::Printer printer(outputFile.get(), '$');

    GenerateBrpcAdapterCppPrologue(printer, file);
    printer.PrintRaw(namespaceBegin);

    for (auto i = 0; i < file.service_count(); ++i) {
        auto *svc = file.service(i);
        const std::string &svcName = svc->name();
        ImplementBrpcServiceBoilerplate(printer, *svc, svcName);
        ImplementBrpcCallMethodDef(printer, *svc, PREFIX, svcName);
        ImplementBrpcDirectCallMethodDef(printer, *svc, PREFIX, svcName);
    }

    printer.PrintRaw(namespaceEnd);
}

void RpcGenerator::GenerateBrpcAdapterCppPrologue(io::Printer &printer,
                                                  const google::protobuf::FileDescriptor &file) const
{
    std::map<std::string, std::string> vars;
    vars["full_file_name"] = file.name();
    vars["file_name"] = fileName;

    std::string impl =
        "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
        "// source: $full_file_name$\n"
        "#include \"$file_name$.brpc.pb.h\"\n"
        "#include <cstring>\n"
        "#include <sys/time.h>\n"
        "#include \"datasystem/common/util/request_context.h\"\n"
        "#include \"datasystem/common/util/thread_local.h\"\n";
    printer.Print(vars, impl.c_str());
}

// ============================================================================
// Brpc CallMethod dispatch helpers
// ============================================================================

void RpcGenerator::ImplementBrpcServiceBoilerplate(io::Printer &printer,
                                                   const google::protobuf::ServiceDescriptor &svc,
                                                   const std::string &svcName) const
{
    std::map<std::string, std::string> vars;
    vars["adapter_name"] = svcName + "BrpcAdapter";
    vars["full_svc_name"] = svc.full_name();
    // GetDescriptor - non-const, uses DescriptorPool
    std::string code =
        "const google::protobuf::ServiceDescriptor* $adapter_name$::GetDescriptor() {\n"
        "    return google::protobuf::DescriptorPool::generated_pool()->FindServiceByName(\"$full_svc_name$\");\n"
        "}\n\n";
    printer.Print(vars, code.c_str());

    // GetRequestPrototype - use method->index() instead of calling GetDescriptor()
    printer.Print(vars, "const google::protobuf::Message& $adapter_name$::GetRequestPrototype(\n"
                        "    const google::protobuf::MethodDescriptor* method) const {\n");
    for (int i = 0; i < svc.method_count(); ++i) {
        const auto *m = svc.method(i);
        vars["idx"] = std::to_string(i);
        vars["req_name"] = m->input_type()->name();
        if (i == 0) {
            printer.Print(vars, "    if (method->index() == $idx$) {\n"
                                "        return $req_name$::default_instance();\n");
        } else {
            printer.Print(vars, "    } else if (method->index() == $idx$) {\n"
                                "        return $req_name$::default_instance();\n");
        }
    }
    printer.PrintRaw("    }\n    LOG(ERROR) << \"Unknown method: \" << method->name();\n"
                     "    return *google::protobuf::MessageFactory::generated_factory()\n"
                     "        ->GetPrototype(method->input_type())->New();\n}\n\n");

    // GetResponsePrototype
    vars["adapter_name"] = svcName + "BrpcAdapter";
    printer.Print(vars, "const google::protobuf::Message& $adapter_name$::GetResponsePrototype(\n"
                        "    const google::protobuf::MethodDescriptor* method) const {\n");
    for (int i = 0; i < svc.method_count(); ++i) {
        const auto *m = svc.method(i);
        vars["idx"] = std::to_string(i);
        vars["rsp_name"] = m->output_type()->name();
        if (i == 0) {
            printer.Print(vars, "    if (method->index() == $idx$) {\n"
                                "        return $rsp_name$::default_instance();\n");
        } else {
            printer.Print(vars, "    } else if (method->index() == $idx$) {\n"
                                "        return $rsp_name$::default_instance();\n");
        }
    }
    printer.PrintRaw("    }\n    LOG(ERROR) << \"Unknown method: \" << method->name();\n"
                     "    return *google::protobuf::MessageFactory::generated_factory()\n"
                     "        ->GetPrototype(method->output_type())->New();\n}\n\n");
}

void RpcGenerator::ImplementBrpcCallMethodDef(io::Printer &printer,
                                              const google::protobuf::ServiceDescriptor &svc,
                                              const std::string &indent,
                                              const std::string &svcName)
{
    const std::string level2Indent = indent + indent;
    std::map<std::string, std::string> vars;
    vars["svcName"] = svcName;
    vars["adapter_name"] = svcName + "BrpcAdapter";

    printer.Print(vars, BuildCallMethodPrologue().c_str());

    for (auto j = 0; j < svc.method_count(); ++j) {
        if (svc.method(j) == nullptr) {
            continue;
        }
        auto &method = *(svc.method(j));
        vars["methodName"] = method.name();
        vars["methodIndex"] = std::to_string(j);
        printer.Print(vars, "        case $methodIndex$: { // $methodName$\n");
        ImplementBrpcMethodVariant(printer, method, j, level2Indent);
        printer.PrintRaw(
            "            return;\n"
            "        }  // case\n");
    }

    printer.PrintRaw(BuildCallMethodEpilogue().c_str());
}

std::string RpcGenerator::BuildCallMethodPrologue()
{
    return
        "void $adapter_name$::CallMethod(const google::protobuf::MethodDescriptor* method,\n"
        "                                google::protobuf::RpcController* cntl_base,\n"
        "                                const google::protobuf::Message* request,\n"
        "                                google::protobuf::Message* response,\n"
        "                                google::protobuf::Closure* done) {\n"
        "    brpc::ClosureGuard done_guard(done);\n"
        "    auto* cntl = static_cast<brpc::Controller*>(cntl_base);\n"
        "    // Extract and strip traceID from request attachment sentinel framing.\n"
        "    // Wire format: [8-byte magic \"TRCID:V1\"][4-byte uint32_t len][traceID bytes]\n"
        "    // The remaining attachment after stripping is the original payload (if any).\n"
        "    std::string rpcTraceID;\n"
        "    butil::IOBuf &_reqBuf = cntl->request_attachment();\n"
        "    const char _traceMagic[8] = {'T','R','C','I','D',':','V','1'};\n"
        "    char _magicBuf[sizeof(_traceMagic)];\n"
        "    constexpr size_t K_MIN_TRACE_ATTACHMENT = sizeof(_traceMagic) + sizeof(uint32_t);\n"
        "    if (_reqBuf.size() >= K_MIN_TRACE_ATTACHMENT &&\n"
        "        _reqBuf.copy_to(_magicBuf, sizeof(_magicBuf)) == sizeof(_magicBuf) &&\n"
        "        std::memcmp(_magicBuf, _traceMagic, sizeof(_traceMagic)) == 0) {\n"
        "        _reqBuf.pop_front(sizeof(_traceMagic));\n"
        "        uint32_t _traceLen = 0;\n"
        "        _reqBuf.copy_to(&_traceLen, sizeof(_traceLen));\n"
        "        _reqBuf.pop_front(sizeof(_traceLen));\n"
        "        if (_traceLen > 0 &&\n"
        "            _traceLen <= static_cast<uint32_t>(::datasystem::Trace::TRACEID_MAX_SIZE) &&\n"
        "            _reqBuf.size() >= _traceLen) {\n"
        "            rpcTraceID.resize(_traceLen);\n"
        "            _reqBuf.copy_to(&rpcTraceID[0], _traceLen);\n"
        "            _reqBuf.pop_front(_traceLen);\n"
        "        }\n"
        "    }\n"
        "    ::datasystem::ScopedRequestContext scopedCtx(rpcTraceID);\n"
        "    switch (method->index()) {\n";
}

std::string RpcGenerator::BuildCallMethodEpilogue()
{
    return
        "        default: {\n"
        "            cntl->SetFailed(\"Unknown method: \" + method->name());\n"
        "\n"
        "            return;\n"
        "        }\n"
        "    } // switch\n"
        "}\n";
}

void RpcGenerator::ImplementBrpcMethodVariant(io::Printer &printer,
                                              const google::protobuf::MethodDescriptor &method, int methodIndex,
                                              const std::string &indent)
{
    (void)indent;
    if (!method.client_streaming() && !method.server_streaming()) {
        if (UnarySocketNeeded(method)) {
            ImplementBrpcCallMethodUnarySocket(printer, method, methodIndex, indent);
        } else if (HasPayloadSendOption(method) || HasPayloadRecvOption(method)) {
            // payload variants (plain, send-only, recv-only, or both)
            if (HasPayloadSendOption(method) && HasPayloadRecvOption(method)) {
                ImplementBrpcCallMethodSendRecvPayload(printer, method, methodIndex, indent);
            } else if (HasPayloadSendOption(method)) {
                ImplementBrpcCallMethodSendPayload(printer, method, methodIndex, indent);
            } else {
                ImplementBrpcCallMethodRecvPayload(printer, method, methodIndex, indent);
            }
        } else {
            ImplementBrpcCallMethodPlain(printer, method, methodIndex, indent);
        }
    } else if (method.client_streaming() && !method.server_streaming()) {
        ImplementBrpcCallMethodClientStream(printer, method, methodIndex, indent);
    } else if (!method.client_streaming() && method.server_streaming()) {
        ImplementBrpcCallMethodServerStream(printer, method, methodIndex, indent);
    } else {
        ImplementBrpcCallMethodBidiStream(printer, method, methodIndex, indent);
    }
}

void RpcGenerator::ImplementBrpcDirectCallMethodDef(io::Printer &printer,
                                                    const google::protobuf::ServiceDescriptor &svc,
                                                    const std::string &indent,
                                                    const std::string &svcName)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["svcName"] = svcName;
    vars["adapter_name"] = svcName + "BrpcAdapter";

    std::string startFunction =
        "::datasystem::Status $adapter_name$::DirectCallMethod(\n"
        "    const google::protobuf::MethodDescriptor* method,\n"
        "    google::protobuf::RpcController* cntl_base,\n"
        "    const google::protobuf::Message* request,\n"
        "    google::protobuf::Message* response,\n"
        "    google::protobuf::Closure* done) {\n"
        "    auto* cntl = static_cast<brpc::Controller*>(cntl_base);\n"
        "    (void)cntl;\n"
        "    switch (method->index()) {\n";
    printer.Print(vars, startFunction.c_str());

    for (auto j = 0; j < svc.method_count(); ++j) {
        if (svc.method(j) == nullptr) {
            continue;
        }
        auto &method = *(svc.method(j));
        if (method.client_streaming() || method.server_streaming()) {
            continue;
        }
        if (UnarySocketNeeded(method)) {
            continue;
        }
        vars["methodName"] = method.name();
        vars["methodIndex"] = std::to_string(j);
        vars["inputTypeName"] = method.input_type()->name();
        vars["outputTypeName"] = method.output_type()->name();
        printer.Print(vars, "        case $methodIndex$: { // $methodName$\n");
        printer.Print(vars, BuildDirectCallCaseCode(method).c_str());
        printer.PrintRaw("        }  // case\n");
    }

    std::string endFunction =
        "        default: {\n"
        "            return ::datasystem::Status(::datasystem::StatusCode::K_UNKNOWN_ERROR,\n"
        "                                        __LINE__, __FILE__, \"Unknown method\");\n"
        "        }\n"
        "    } // switch\n"
        "}\n";
    printer.PrintRaw(endFunction);
}

std::string RpcGenerator::BuildDirectCallCaseCode(const google::protobuf::MethodDescriptor &method)
{
    if (!HasPayloadSendOption(method) && !HasPayloadRecvOption(method)) {
        return std::string(
            "            auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
            "            auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
            "            if (req == nullptr || rsp == nullptr) {\n"
            "                return ::datasystem::Status(::datasystem::StatusCode::K_RUNTIME_ERROR,\n"
            "                    __LINE__, __FILE__, \"Type mismatch for $methodName$\");\n"
            "            }\n"
            "            return impl_.$methodName$(*req, *rsp);\n");
    }
    // Payload variants: not supported in DirectCallMethod yet
    return std::string(
        "            return ::datasystem::Status(::datasystem::StatusCode::K_NOT_SUPPORTED,\n"
        "                __LINE__, __FILE__, \"DirectCallMethod with payload not yet supported\");\n");
}

// --- Pattern 1: plain (no payloads, no sockets) ---

void RpcGenerator::ImplementBrpcCallMethodPlain(io::Printer &printer,
                                                const google::protobuf::MethodDescriptor &method,
                                                int methodIndex,
                                                const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    std::string impl =
        "$indent$auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
        "$indent$auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
        "$indent$if (req == nullptr || rsp == nullptr) {\n"
        "$indent$    cntl->SetFailed(\"Request/response type mismatch for $methodName$\");\n"
        "$indent$    return;\n"
        "$indent$}\n";
    impl += BuildScTimeoutDurationInitSnippet();
    impl +=
        "$indent$::datasystem::Status st = impl_.$methodName$(*req, *rsp);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01\" \"DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$}\n";
    printer.Print(vars, impl.c_str());
}

// --- Pattern 2: send_payload ---

void RpcGenerator::ImplementBrpcCallMethodSendPayload(io::Printer &printer,
                                                      const google::protobuf::MethodDescriptor &method,
                                                      int methodIndex,
                                                      const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    // Wire format in IOBuf: [int64_t count][int64_t size1][data1][int64_t size2][data2]...
    // The brpc client stub writes payload in this same framing format.
    std::string impl =
        "$indent$auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
        "$indent$auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
        "$indent$if (req == nullptr || rsp == nullptr) {\n"
        "$indent$    cntl->SetFailed(\"Request/response type mismatch for $methodName$\");\n"
        "$indent$    return;\n"
        "$indent$}\n"
        "$indent$std::vector<::datasystem::RpcMessage> payload;\n"
        "$indent$butil::IOBuf &attachment = cntl->request_attachment();\n"
        "$indent$do {\n"
        "$indent$    if (attachment.empty()) { break; }\n"
        "$indent$    int64_t count = 0;\n"
        "$indent$    if (attachment.copy_to(reinterpret_cast<void*>(&count), sizeof(count)) != sizeof(count)) "
        "{ break; }\n"
        "$indent$    attachment.pop_front(sizeof(count));\n"
        "$indent$    payload.resize(static_cast<size_t>(count));\n"
        "$indent$    for (auto& msg : payload) {\n"
        "$indent$        int64_t sz = 0;\n"
        "$indent$        if (attachment.copy_to(reinterpret_cast<void*>(&sz), sizeof(sz)) != sizeof(sz)) { break; }\n"
        "$indent$        attachment.pop_front(sizeof(sz));\n"
        "$indent$        if (msg.Resize(static_cast<size_t>(sz)).IsError()) { break; }\n"
        "$indent$        if (attachment.copy_to(msg.Data(), static_cast<size_t>(sz)) != static_cast<size_t>(sz)) "
        "{ break; }\n"
        "$indent$        attachment.pop_front(static_cast<size_t>(sz));\n"
        "$indent$    }\n"
        "$indent$} while (false);\n";
    impl += BuildScTimeoutDurationInitSnippet();
    impl +=
        "$indent$::datasystem::Status st = impl_.$methodName$(*req, *rsp, std::move(payload));\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01\" \"DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$}\n";
    printer.Print(vars, impl.c_str());
}

// --- Pattern 3: recv_payload ---

void RpcGenerator::ImplementBrpcCallMethodRecvPayload(io::Printer &printer,
                                                      const google::protobuf::MethodDescriptor &method,
                                                      int methodIndex,
                                                      const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    // Wire format in IOBuf: [int64_t count][int64_t size1][data1][int64_t size2][data2]...
    std::string impl =
        "$indent$auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
        "$indent$auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
        "$indent$if (req == nullptr || rsp == nullptr) {\n"
        "$indent$    cntl->SetFailed(\"Request/response type mismatch for $methodName$\");\n"
        "$indent$    return;\n"
        "$indent$}\n"
        "$indent$std::vector<::datasystem::RpcMessage> outPayload;\n";
    impl += BuildScTimeoutDurationInitSnippet();
    impl +=
        "$indent$::datasystem::Status st = impl_.$methodName$(*req, *rsp, outPayload);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01\" \"DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$} else {\n"
        "$indent$    auto& buf = cntl->response_attachment();\n"
        "$indent$    int64_t count = static_cast<int64_t>(outPayload.size());\n"
        "$indent$    buf.append(reinterpret_cast<const void*>(&count), sizeof(count));\n"
        "$indent$    for (auto& msg : outPayload) {\n"
        "$indent$        int64_t sz = static_cast<int64_t>(msg.Size());\n"
        "$indent$        buf.append(reinterpret_cast<const void*>(&sz), sizeof(sz));\n"
        "$indent$        buf.append(msg.Data(), msg.Size());\n"
        "$indent$    }\n"
        "$indent$}\n";
    printer.Print(vars, impl.c_str());
}

// --- Pattern 2+3 combined: send_payload + recv_payload ---

void RpcGenerator::ImplementBrpcCallMethodSendRecvPayload(io::Printer &printer,
                                                          const google::protobuf::MethodDescriptor &method,
                                                          int methodIndex,
                                                          const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    // Wire format in IOBuf: [int64_t count][int64_t size1][data1][int64_t size2][data2]...
    std::string impl = BuildSendRecvPayloadImpl();
    printer.Print(vars, impl.c_str());
}

std::string RpcGenerator::BuildSendRecvPayloadImpl()
{
    return BuildScTimeoutDurationInitSnippet() +
        "$indent$auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
        "$indent$auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
        "$indent$if (req == nullptr || rsp == nullptr) {\n"
        "$indent$    cntl->SetFailed(\"Request/response type mismatch for $methodName$\");\n"
        "$indent$    return;\n"
        "$indent$}\n"
        "$indent$std::vector<::datasystem::RpcMessage> payload;\n"
        "$indent$std::vector<::datasystem::RpcMessage> outPayload;\n"
        "$indent$// Deserialize request_attachment -> payload\n"
        "$indent$butil::IOBuf &reqBuf = cntl->request_attachment();\n"
        "$indent$do {\n"
        "$indent$    if (reqBuf.empty()) { break; }\n"
        "$indent$    int64_t count = 0;\n"
        "$indent$    if (reqBuf.copy_to(reinterpret_cast<void*>(&count), sizeof(count)) != sizeof(count)) { break; }\n"
        "$indent$    reqBuf.pop_front(sizeof(count));\n"
        "$indent$    payload.resize(static_cast<size_t>(count));\n"
        "$indent$    for (auto& msg : payload) {\n"
        "$indent$        int64_t sz = 0;\n"
        "$indent$        if (reqBuf.copy_to(reinterpret_cast<void*>(&sz), sizeof(sz)) != sizeof(sz)) { break; }\n"
        "$indent$        reqBuf.pop_front(sizeof(sz));\n"
        "$indent$        if (msg.Resize(static_cast<size_t>(sz)).IsError()) { break; }\n"
        "$indent$        if (reqBuf.copy_to(msg.Data(), static_cast<size_t>(sz)) != static_cast<size_t>(sz)) "
        "{ break; }\n"
        "$indent$        reqBuf.pop_front(static_cast<size_t>(sz));\n"
        "$indent$    }\n"
        "$indent$} while (false);\n"
        "$indent$::datasystem::Status st = impl_.$methodName$(*req, *rsp, std::move(payload), outPayload);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01\" \"DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$} else {\n"
        "$indent$    // Serialize outPayload -> response_attachment\n"
        "$indent$    auto& rspBuf = cntl->response_attachment();\n"
        "$indent$    int64_t count = static_cast<int64_t>(outPayload.size());\n"
        "$indent$    rspBuf.append(reinterpret_cast<const void*>(&count), sizeof(count));\n"
        "$indent$    for (auto& msg : outPayload) {\n"
        "$indent$        int64_t sz = static_cast<int64_t>(msg.Size());\n"
        "$indent$        rspBuf.append(reinterpret_cast<const void*>(&sz), sizeof(sz));\n"
        "$indent$        rspBuf.append(msg.Data(), msg.Size());\n"
        "$indent$    }\n"
        "$indent$}\n";
}

// --- Pattern 4: unary_socket ---

void RpcGenerator::ImplementBrpcCallMethodUnarySocket(io::Printer &printer,
                                                      const google::protobuf::MethodDescriptor &method,
                                                      int methodIndex,
                                                      const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    std::string impl =
        "$indent$// UnarySocket pattern: async completion via done closure.\n"
        "$indent$// Release done from ClosureGuard so serverApi owns it.\n"
        "$indent$google::protobuf::Closure* asyncDone = done_guard.release();\n"
        "$indent$auto serverApi =\n"
        "$indent$    std::make_shared<::datasystem::BrpcServerUnaryWriterReader<$outputTypeName$, $inputTypeName$>>(\n"
        "$indent$        cntl, request, response, asyncDone);\n";
    if (HasPayloadRecvOption(method)) {
        impl +=
        "$indent$// Defer done_->Run() so SendPayload()/SendAndTagPayload() can write\n"
        "$indent$// payload to response_attachment before brpc serializes the response.\n"
        "$indent$serverApi->SetHasRecvPayload(true);\n";
    }
    impl += BuildScTimeoutDurationInitSnippet();
    impl +=
        "$indent$// Keep both request timeout domains aligned with the brpc deadline.\n"
        "$indent$GetRequestContext()->reqTimeoutDuration = serverApi->GetScTimeoutDuration();\n"
        "$indent$GetRequestContext()->scTimeoutDuration = serverApi->GetScTimeoutDuration();\n"
        "$indent$::datasystem::Status st = impl_.$methodName$(serverApi);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    VLOG(1) << \"[BRPC_UNARY_SOCKET_SET_FAILED] method=$methodName$\"\n"
        "$indent$            << \", status=\" << st.ToString()\n"
        "$indent$            << \", dsErrCode=\" << static_cast<int>(st.GetCode())\n"
        "$indent$            << \", remoteSide=\" << cntl->remote_side()\n"
        "$indent$            << \", localSide=\" << cntl->local_side();\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01\" \"DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$    // Run done exactly once to send the error response. The service impl may\n"
        "$indent$    // have already Run() it via SendStatus()/Write() (brpc NewCallback closures\n"
        "$indent$    // self-delete after Run, so a second asyncDone->Run() would be a UAF).\n"
        "$indent$    // RunDoneIfNotConsumed() CAS-gates on doneConsumed_, so it only Run()s when\n"
        "$indent$    // the service returned an error without completing the RPC itself.\n"
        "$indent$    serverApi->RunDoneIfNotConsumed();\n"
        "$indent$}\n"
        "$indent$// If st.IsOk(), done->Run() will be called by Write()/SendStatus()\n"
        "$indent$// (or by SendPayload()/SendAndTagPayload() when SetHasRecvPayload(true)).\n"
        "$indent$// Falls back to ~BrpcServerUnaryWriterReader() if none are called.\n";
    printer.Print(vars, impl.c_str());
}

std::string RpcGenerator::BuildScTimeoutDurationInitSnippet()
{
    return
        "$indent$// Init per-request timeout so worker-side retry loops (e.g.\n"
        "$indent$// TryGetObjectFromRemote) and worker->master RPCs use the client\n"
        "$indent$// deadline, not the 60s default.\n"
        "$indent$//\n"
        "$indent$// brpc server-side Controller::deadline_us() is NOT set from the\n"
        "$indent$// client timeout_ms propagated in RpcMeta: baidu_rpc_protocol.cpp only\n"
        "$indent$// calls cntl->set_timeout_ms(request_meta.timeout_ms()), which sets\n"
        "$indent$// _timeout_ms/_real_timeout_ms but leaves _deadline_us = -1 (deadline_us\n"
        "$indent$// is a client-side absolute timestamp the server never reconstructs).\n"
        "$indent$// So on brpc server entry deadline_us() is almost always -1, and the\n"
        "$indent$// previous code fell back to Init() (60s default), dropping the client\n"
        "$indent$// budget entirely (issue #773: client 20ms budget lost, worker->master\n"
        "$indent$// CreateMeta ran with 60s; during SCALE_OUT meta migration the worker\n"
        "$indent$// retried for 255ms and returned OK while the client had timed out).\n"
        "$indent$//\n"
        "$indent$// Prefer deadline_us() when present (internal RPC forward preserving an\n"
        "$indent$// absolute deadline); otherwise fall back to timeout_ms() (the relative\n"
        "$indent$// client budget restored by brpc from RpcMeta). Only use the 60s default\n"
        "$indent$// when neither is set (background/internal call with no client deadline).\n"
        "$indent${\n"
        "$indent$    int64_t deadlineUs = cntl->deadline_us();\n"
        "$indent$    int64_t remainingMs = 0;\n"
        "$indent$    if (deadlineUs > 0) {\n"
        "$indent$        struct timeval tv;\n"
        "$indent$        gettimeofday(&tv, nullptr);\n"
        "$indent$        int64_t nowUs = static_cast<int64_t>(tv.tv_sec) * 1000000L + tv.tv_usec;\n"
        "$indent$        // Round up (F17): integer truncation would turn (0, 999us] into 0ms,\n"
        "$indent$        // causing GetRequestContext()->scTimeoutDuration.Init() with default (infinite) timeout.\n"
        "$indent$        remainingMs = (deadlineUs - nowUs + 999) / 1000;\n"
        "$indent$    }\n"
        "$indent$    // If the absolute deadline is absent (brpc server entry, which never\n"
        "$indent$    // reconstructs _deadline_us from wire RpcMeta), fall back to timeout_ms()\n"
        "$indent$    // — the relative client budget that brpc delivers via RpcMeta.timeout_ms\n"
        "$indent$    // when baidu_std_protocol_deliver_timeout_ms is enabled on the client side.\n"
        "$indent$    // Only use the 60s default when neither is available.\n"
        "$indent$    //\n"
        "$indent$    // When deadline_us > 0 but the deadline has passed (remainingMs <= 0),\n"
        "$indent$    // the budget is genuinely exhausted — do NOT fall back to timeout_ms(),\n"
        "$indent$    // which would extend the request beyond its original absolute deadline.\n"
        "$indent$    //\n"
        "$indent$    // Note: timeout_ms() is the client's send-time relative budget; brpc does\n"
        "$indent$    // not subtract the wire RTT when the server restores it, so the server-side\n"
        "$indent$    // remaining may overestimate the true remaining by one network RTT. This\n"
        "$indent$    // is an acceptable approximation for the retry/backoff use case and is\n"
        "$indent$    // strictly better than the previous 60s fallback.\n"
        "$indent$    if (deadlineUs <= 0 && cntl->timeout_ms() > 0) {\n"
        "$indent$        remainingMs = cntl->timeout_ms();\n"
        "$indent$    }\n"
        "$indent$    if (remainingMs > 0) {\n"
        "$indent$        GetRequestContext()->reqTimeoutDuration.Init(remainingMs);\n"
        "$indent$        GetRequestContext()->scTimeoutDuration.Init(remainingMs);\n"
        "$indent$    } else {\n"
        "$indent$        GetRequestContext()->reqTimeoutDuration.Init();\n"
        "$indent$        GetRequestContext()->scTimeoutDuration.Init();\n"
        "$indent$    }\n"
        "$indent$}\n";
}

// --- Streaming patterns ---

void RpcGenerator::ImplementBrpcCallMethodClientStream(io::Printer &printer,
                                                       const google::protobuf::MethodDescriptor &method,
                                                       int methodIndex,
                                                       const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["optRecvPayload1"] = HasPayloadRecvOption(method) ? ", outPayload" : "";

    // Client-streaming (stream->unary): server reads N requests from the
    // brpc stream, then returns a single response via the RPC response body.
    std::string impl =
        "$indent$// Client-streaming via BrpcServerReaderImpl\n"
        "$indent$auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
        "$indent$if (rsp == nullptr) {\n"
        "$indent$    cntl->SetFailed(\"Response type mismatch for $methodName$\");\n"
        "$indent$    return;\n"
        "$indent$}\n";
    if (HasPayloadRecvOption(method)) {
        impl +=
        "$indent$std::vector<::datasystem::RpcMessage> outPayload;\n";
    }
    impl +=
        "$indent$auto pimpl =\n"
        "$indent$    std::make_shared<::datasystem::BrpcServerReaderImpl<$inputTypeName$>>(cntl,\n"
        "\"$methodFullName$\");\n"
        "$indent$// Arm self-keepalive: shared_from_this() requires the object to already be\n"
        "$indent$// managed by a shared_ptr, so it cannot run in the ctor. Must run after\n"
        "$indent$// make_shared and before pimpl is moved into ServerReader.\n"
        "$indent$pimpl->Init();\n"
        "$indent$// Sync adapter's scTimeoutDuration to RequestContext before pimpl is moved.\n"
        "$indent$GetRequestContext()->scTimeoutDuration = pimpl->GetScTimeoutDuration();\n"
        "$indent$auto reader =\n"
        "$indent$    std::make_shared<::datasystem::ServerReader<$inputTypeName$>>(std::move(pimpl));\n"
        "$indent${\n";
    impl += BuildScTimeoutDurationInitSnippet();
    impl +=
        "$indent$}\n"
        "$indent$$outputTypeName$ reply;\n"
        "$indent$::datasystem::Status st = impl_.$methodName$(reader, reply$optRecvPayload1$);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01\" \"DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$} else {\n"
        "$indent$    rsp->CopyFrom(reply);\n"
        "$indent$}\n";
    printer.Print(vars, impl.c_str());
}

void RpcGenerator::ImplementBrpcCallMethodServerStream(io::Printer &printer,
                                                       const google::protobuf::MethodDescriptor &method,
                                                       int methodIndex,
                                                       const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["optSendPayload1"] = HasPayloadSendOption(method) ? ", std::move(pl)" : "";

    // Server-streaming (unary->stream): server reads the request from RPC
    // body, then writes N responses via brpc::StreamWrite.
    std::string impl =
        "$indent$// Server-streaming via BrpcServerWriterImpl\n"
        "$indent$auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
        "$indent$if (req == nullptr) {\n"
        "$indent$    cntl->SetFailed(\"Request type mismatch for $methodName$\");\n"
        "$indent$    return;\n"
        "$indent$}\n";
    if (HasPayloadSendOption(method)) {
        impl +=
        "$indent$std::vector<::datasystem::RpcMessage> pl;\n";
    }
    impl +=
        "$indent$auto pimpl =\n"
        "$indent$    std::make_unique<::datasystem::BrpcServerWriterImpl<$outputTypeName$>>(\n"
        "$indent$        cntl, request, \"$methodFullName$\");\n"
        "$indent$// Sync adapter's scTimeoutDuration to RequestContext before pimpl is moved.\n"
        "$indent$GetRequestContext()->scTimeoutDuration = pimpl->GetScTimeoutDuration();\n"
        "$indent$auto writer =\n"
        "$indent$    std::make_shared<::datasystem::ServerWriter<$outputTypeName$>>(std::move(pimpl));\n"
        "$indent${\n";
    impl += BuildScTimeoutDurationInitSnippet();
    impl +=
        "$indent$}\n"
        "$indent$$inputTypeName$ rq;\n";
    if (HasPayloadSendOption(method)) {
        impl +=
        "$indent$// Receive payload from request_attachment\n"
        "$indent$butil::IOBuf &reqBuf = cntl->request_attachment();\n"
        "$indent$do {\n"
        "$indent$    if (reqBuf.empty()) { break; }\n"
        "$indent$    int64_t count = 0;\n"
        "$indent$    if (reqBuf.copy_to(reinterpret_cast<void*>(&count), sizeof(count)) != sizeof(count)) { break; }\n"
        "$indent$    reqBuf.pop_front(sizeof(count));\n"
        "$indent$    pl.resize(static_cast<size_t>(count));\n"
        "$indent$    for (auto& msg : pl) {\n"
        "$indent$        int64_t sz = 0;\n"
        "$indent$        if (reqBuf.copy_to(reinterpret_cast<void*>(&sz), sizeof(sz)) != sizeof(sz)) { break; }\n"
        "$indent$        reqBuf.pop_front(sizeof(sz));\n"
        "$indent$        if (msg.Resize(static_cast<size_t>(sz)).IsError()) { break; }\n"
        "$indent$        if (reqBuf.copy_to(msg.Data(), static_cast<size_t>(sz))"
        " != static_cast<size_t>(sz)) { break; }\n"
        "$indent$        reqBuf.pop_front(static_cast<size_t>(sz));\n"
        "$indent$    }\n"
        "$indent$} while (false);\n";
    }
    impl +=
        "$indent$::datasystem::Status readSt = writer->ReadPb(rq);\n"
        "$indent$if (readSt.IsError()) {\n"
        "$indent$    cntl->SetFailed(readSt.GetMsg() + \"\\x01\" \"DS_ERR:\" + "
        "std::to_string(static_cast<int>(readSt.GetCode())) + \"\\x02\");\n"
        "$indent$    return;\n"
        "$indent$}\n"
        "$indent$::datasystem::Status st = impl_.$methodName$(writer, rq$optSendPayload1$);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01\" \"DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$}\n";
    printer.Print(vars, impl.c_str());
}

void RpcGenerator::ImplementBrpcCallMethodBidiStream(io::Printer &printer,
                                                     const google::protobuf::MethodDescriptor &method,
                                                     int methodIndex,
                                                     const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    // Bidi-streaming pattern: create BrpcServerWriterReaderImpl wrapper
    // The service implementation reads the request from RPC body and writes
    // N responses via brpc::StreamWrite through the ServerWriterReaderBase interface.
    std::string impl =
        "$indent$// Bidi-streaming via BrpcServerWriterReaderImpl\n"
        "$indent$auto brpcStreamImpl =\n"
        "$indent$    std::make_unique<::datasystem::BrpcServerWriterReaderImpl<$outputTypeName$, $inputTypeName$>>(\n"
        "$indent$        cntl, request, \"$methodFullName$\");\n"
        "$indent$// Sync adapter's scTimeoutDuration to RequestContext before brpcStreamImpl is moved.\n"
        "$indent$GetRequestContext()->scTimeoutDuration = brpcStreamImpl->GetScTimeoutDuration();\n"
        "$indent$auto stream =\n"
        "$indent$    std::make_shared<::datasystem::ServerWriterReader<$outputTypeName$, $inputTypeName$>>("
        "std::move(brpcStreamImpl));\n";
    impl += BuildScTimeoutDurationInitSnippet();
    impl +=
        "$indent$::datasystem::Status st = impl_.$methodName$(stream);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01\" \"DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$}\n";
    printer.Print(vars, impl.c_str());
}

}  // namespace datasystem
