/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2022. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Description: Brpc adapter generator (V8 three-output pattern).
 * Generates {ServiceName}BrpcAdapter classes that wrap I{ServiceName} and
 * implement brpc::Service for brpc integration.
 */
#include "datasystem/common/rpc/plugin_generator/zmq_rpc_generator.h"

#include <google/protobuf/descriptor.h>

namespace datasystem {

// --- Brpc adapter header ---

void ZmqRpcGenerator::CreateBrpcAdapterHeader(const google::protobuf::FileDescriptor &file,
                                              compiler::GeneratorContext *generatorCtx) const
{
    std::unique_ptr<io::ZeroCopyOutputStream> outputFile(generatorCtx->Open(fileName + ".brpc.pb.h"));
    io::Printer printer(outputFile.get(), '$');

    GenerateBrpcAdapterPrologue(printer, file);
    printer.PrintRaw(namespaceBegin);

    for (auto i = 0; i < file.service_count(); ++i) {
        auto *svc = file.service(i);
        GenerateBrpcAdapter(printer, *svc, PREFIX);
    }

    printer.PrintRaw(namespaceEnd);
    printer.PrintRaw(ENDIF);
}

void ZmqRpcGenerator::GenerateBrpcAdapterPrologue(io::Printer &printer,
                                                  const google::protobuf::FileDescriptor &file) const
{
    std::map<std::string, std::string> vars;
    vars["full_file_name"] = file.name();
    vars["file_name"] = fileName;
    std::string fileNameHeader = fileName;
    std::replace(fileNameHeader.begin(), fileNameHeader.end(), '/', '_');
    vars["file_name_header"] = fileNameHeader;
    std::string impl =
        "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
        "// source: $full_file_name$\n"
        "#ifndef DATASYSTEM_PROTO_BRPC_$file_name_header$_ADAPTER_H\n"
        "#define DATASYSTEM_PROTO_BRPC_$file_name_header$_ADAPTER_H\n"
        "#include <memory>\n"
        "#include <vector>\n";
    if (file.message_type_count() > 0) {
        impl += "#include \"$file_name$.pb.h\"\n";
    }
    impl +=
        "#include \"$file_name$.irpc.pb.h\"\n"
        "#include <google/protobuf/service.h>\n"
        "#include <brpc/controller.h>\n"
        "#include <brpc/stream.h>\n"
        "#include \"datasystem/common/rpc/brpc_server_unary_writer_reader.h\"\n"
        "#include \"datasystem/common/rpc/brpc_server_writer_reader_impl.h\"\n"
        "#include \"datasystem/common/rpc/rpc_message.h\"\n"
        "#include \"datasystem/utils/status.h\"\n";
    printer.Print(vars, impl.c_str());
    for (auto k = 0; k < file.dependency_count(); ++k) {
        auto depend = file.dependency(k)->name();
        bool isAProto = StripSuffix(depend, ".proto");
        if (isAProto) {
            vars["depend"] = depend;
            printer.Print(vars, "#include \"$depend$.pb.h\"\n");
        }
    }
    printer.PrintRaw("#include <string>\n");
}

void ZmqRpcGenerator::GenerateBrpcAdapter(io::Printer &printer, const google::protobuf::ServiceDescriptor &svc,
                                          const std::string &indent) const
{
    (void)indent;
    const std::string &svcName = svc.name();
    std::map<std::string, std::string> vars;
    vars["svc_name"] = svcName;
    vars["interface_name"] = "I" + svcName;
    vars["adapter_name"] = svcName + "BrpcAdapter";

    // Build method descriptor entries for GetDescriptor/GetRequestPrototype/GetResponsePrototype
    std::string methodDescriptors;
    for (int i = 0; i < svc.method_count(); ++i) {
        const auto *method = svc.method(i);
        vars["method_name"] = method->name();
        vars["req_name"] = method->input_type()->name();
        vars["rsp_name"] = method->output_type()->name();
        vars["idx"] = std::to_string(i);
        methodDescriptors +=
            "    static const google::protobuf::MethodDescriptor* method_descriptor_$idx$;\n"
            "    static const $req_name$& request_prototype_$idx$;\n"
            "    static const $rsp_name$& response_prototype_$idx$;\n";
    }

    std::string impl =
        "class $adapter_name$ : public google::protobuf::Service {\n"
        "public:\n"
        "    typedef $interface_name$ Interface;\n"
        "    explicit $adapter_name$($interface_name$ &impl) : impl_(impl) {}\n"
        "    ~$adapter_name$() override = default;\n"
        "    const google::protobuf::ServiceDescriptor* GetDescriptor() override;\n"
        "    const google::protobuf::Message& GetRequestPrototype(\n"
        "        const google::protobuf::MethodDescriptor* method) const override;\n"
        "    const google::protobuf::Message& GetResponsePrototype(\n"
        "        const google::protobuf::MethodDescriptor* method) const override;\n"
        "    void CallMethod(const google::protobuf::MethodDescriptor* method,\n"
        "                    google::protobuf::RpcController* cntl_base,\n"
        "                    const google::protobuf::Message* request,\n"
        "                    google::protobuf::Message* response,\n"
        "                    google::protobuf::Closure* done) override;\n"
        "    ::datasystem::Status DirectCallMethod(const google::protobuf::MethodDescriptor* method,\n"
        "                                          google::protobuf::RpcController* cntl_base,\n"
        "                                          const google::protobuf::Message* request,\n"
        "                                          google::protobuf::Message* response,\n"
        "                                          google::protobuf::Closure* done);\n"
        "private:\n"
        "    $interface_name$ &impl_;\n"
        "};\n";
    printer.Print(vars, impl.c_str());
}

// --- Brpc adapter cpp ---

void ZmqRpcGenerator::CreateBrpcAdapterCpp(const google::protobuf::FileDescriptor &file,
                                           compiler::GeneratorContext *generatorCtx) const
{
    std::unique_ptr<io::ZeroCopyOutputStream> outputFile(generatorCtx->Open(fileName + ".brpc.pb.cc"));
    io::Printer printer(outputFile.get(), '$');

    GenerateBrpcAdapterCppPrologue(printer, file);
    printer.PrintRaw(namespaceBegin);

    for (auto i = 0; i < file.service_count(); ++i) {
        auto *svc = file.service(i);
        const std::string &svcName = svc->name();
        ImplementBrpcServiceBoilerplate(printer, *svc, svcName);
        ImplementBrpcCallMethodDef(printer, *svc, PREFIX, svcName);
        ImplementBrpcDirectCallMethodDef(printer, *svc, PREFIX, svcName);
    }

    printer.PrintRaw(namespaceEnd);
}

void ZmqRpcGenerator::GenerateBrpcAdapterCppPrologue(io::Printer &printer,
                                                     const google::protobuf::FileDescriptor &file) const
{
    std::map<std::string, std::string> vars;
    vars["full_file_name"] = file.name();
    vars["file_name"] = fileName;

    std::string impl =
        "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
        "// source: $full_file_name$\n"
        "#include \"$file_name$.brpc.pb.h\"\n"
        "#include <sys/time.h>\n"
        "#include \"datasystem/common/util/thread_local.h\"\n";
    printer.Print(vars, impl.c_str());
}

// ============================================================================
// Brpc CallMethod dispatch helpers
// ============================================================================

void ZmqRpcGenerator::ImplementBrpcServiceBoilerplate(io::Printer &printer,
                                                      const google::protobuf::ServiceDescriptor &svc,
                                                      const std::string &svcName) const
{
    std::map<std::string, std::string> vars;
    vars["adapter_name"] = svcName + "BrpcAdapter";
    vars["full_svc_name"] = svc.full_name();
    // GetDescriptor - non-const, uses DescriptorPool
    std::string code =
        "const google::protobuf::ServiceDescriptor* $adapter_name$::GetDescriptor() {\n"
        "    return google::protobuf::DescriptorPool::generated_pool()->FindServiceByName(\"$full_svc_name$\");\n"
        "}\n\n";
    printer.Print(vars, code.c_str());

    // GetRequestPrototype - use method->index() instead of calling GetDescriptor()
    printer.Print(vars, "const google::protobuf::Message& $adapter_name$::GetRequestPrototype(\n"
                        "    const google::protobuf::MethodDescriptor* method) const {\n");
    for (int i = 0; i < svc.method_count(); ++i) {
        const auto *m = svc.method(i);
        vars["idx"] = std::to_string(i);
        vars["req_name"] = m->input_type()->name();
        if (i == 0) {
            printer.Print(vars, "    if (method->index() == $idx$) {\n"
                                "        return $req_name$::default_instance();\n");
        } else {
            printer.Print(vars, "    } else if (method->index() == $idx$) {\n"
                                "        return $req_name$::default_instance();\n");
        }
    }
    printer.PrintRaw("    }\n    LOG(ERROR) << \"Unknown method: \" << method->name();\n"
                     "    return *google::protobuf::MessageFactory::generated_factory()\n"
                     "        ->GetPrototype(method->input_type())->New();\n}\n\n");

    // GetResponsePrototype
    vars["adapter_name"] = svcName + "BrpcAdapter";
    printer.Print(vars, "const google::protobuf::Message& $adapter_name$::GetResponsePrototype(\n"
                        "    const google::protobuf::MethodDescriptor* method) const {\n");
    for (int i = 0; i < svc.method_count(); ++i) {
        const auto *m = svc.method(i);
        vars["idx"] = std::to_string(i);
        vars["rsp_name"] = m->output_type()->name();
        if (i == 0) {
            printer.Print(vars, "    if (method->index() == $idx$) {\n"
                                "        return $rsp_name$::default_instance();\n");
        } else {
            printer.Print(vars, "    } else if (method->index() == $idx$) {\n"
                                "        return $rsp_name$::default_instance();\n");
        }
    }
    printer.PrintRaw("    }\n    LOG(ERROR) << \"Unknown method: \" << method->name();\n"
                     "    return *google::protobuf::MessageFactory::generated_factory()\n"
                     "        ->GetPrototype(method->output_type())->New();\n}\n\n");
}

void ZmqRpcGenerator::ImplementBrpcCallMethodDef(io::Printer &printer,
                                                 const google::protobuf::ServiceDescriptor &svc,
                                                 const std::string &indent,
                                                 const std::string &svcName)
{
    const std::string level2Indent = indent + indent;
    std::map<std::string, std::string> vars;
    vars["svcName"] = svcName;
    vars["adapter_name"] = svcName + "BrpcAdapter";

    std::string startFunction =
        "void $adapter_name$::CallMethod(const google::protobuf::MethodDescriptor* method,\n"
        "                                google::protobuf::RpcController* cntl_base,\n"
        "                                const google::protobuf::Message* request,\n"
        "                                google::protobuf::Message* response,\n"
        "                                google::protobuf::Closure* done) {\n"
        "    brpc::ClosureGuard done_guard(done);\n"
        "    auto* cntl = static_cast<brpc::Controller*>(cntl_base);\n"
        "    switch (method->index()) {\n";
    printer.Print(vars, startFunction.c_str());

    for (auto j = 0; j < svc.method_count(); ++j) {
        if (svc.method(j) == nullptr) {
            continue;
        }
        auto &method = *(svc.method(j));
        vars["methodName"] = method.name();
        vars["methodIndex"] = std::to_string(j);
        printer.Print(vars, "        case $methodIndex$: { // $methodName$\n");
        ImplementBrpcMethodVariant(printer, method, j, level2Indent);
        printer.PrintRaw(
            "            return;\n"
            "        }  // case\n");
    }

    std::string endFunction =
        "        default: {\n"
        "            cntl->SetFailed(\"Unknown method: \" + method->name());\n"
        "\n"
        "            return;\n"
        "        }\n"
        "    } // switch\n"
        "}\n";
    printer.PrintRaw(endFunction);
}

void ZmqRpcGenerator::ImplementBrpcMethodVariant(io::Printer &printer,
                                                 const google::protobuf::MethodDescriptor &method, int methodIndex,
                                                 const std::string &indent)
{
    (void)indent;
    if (!method.client_streaming() && !method.server_streaming()) {
        if (UnarySocketNeeded(method)) {
            ImplementBrpcCallMethodUnarySocket(printer, method, methodIndex, indent);
        } else if (HasPayloadSendOption(method) || HasPayloadRecvOption(method)) {
            // payload variants (plain, send-only, recv-only, or both)
            if (HasPayloadSendOption(method) && HasPayloadRecvOption(method)) {
                ImplementBrpcCallMethodSendRecvPayload(printer, method, methodIndex, indent);
            } else if (HasPayloadSendOption(method)) {
                ImplementBrpcCallMethodSendPayload(printer, method, methodIndex, indent);
            } else {
                ImplementBrpcCallMethodRecvPayload(printer, method, methodIndex, indent);
            }
        } else {
            ImplementBrpcCallMethodPlain(printer, method, methodIndex, indent);
        }
    } else if (method.client_streaming() && !method.server_streaming()) {
        ImplementBrpcCallMethodClientStream(printer, method, methodIndex, indent);
    } else if (!method.client_streaming() && method.server_streaming()) {
        ImplementBrpcCallMethodServerStream(printer, method, methodIndex, indent);
    } else {
        ImplementBrpcCallMethodBidiStream(printer, method, methodIndex, indent);
    }
}

void ZmqRpcGenerator::ImplementBrpcDirectCallMethodDef(io::Printer &printer,
                                                       const google::protobuf::ServiceDescriptor &svc,
                                                       const std::string &indent,
                                                       const std::string &svcName)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["svcName"] = svcName;
    vars["adapter_name"] = svcName + "BrpcAdapter";

    std::string startFunction =
        "::datasystem::Status $adapter_name$::DirectCallMethod(\n"
        "    const google::protobuf::MethodDescriptor* method,\n"
        "    google::protobuf::RpcController* cntl_base,\n"
        "    const google::protobuf::Message* request,\n"
        "    google::protobuf::Message* response,\n"
        "    google::protobuf::Closure* done) {\n"
        "    auto* cntl = static_cast<brpc::Controller*>(cntl_base);\n"
        "    (void)cntl;\n"
        "    switch (method->index()) {\n";
    printer.Print(vars, startFunction.c_str());

    for (auto j = 0; j < svc.method_count(); ++j) {
        if (svc.method(j) == nullptr) {
            continue;
        }
        auto &method = *(svc.method(j));
        if (method.client_streaming() || method.server_streaming()) {
            continue;
        }
        if (UnarySocketNeeded(method)) {
            continue;
        }
        vars["methodName"] = method.name();
        vars["methodIndex"] = std::to_string(j);
        vars["inputTypeName"] = method.input_type()->name();
        vars["outputTypeName"] = method.output_type()->name();
        printer.Print(vars, "        case $methodIndex$: { // $methodName$\n");
        printer.Print(vars, BuildDirectCallCaseCode(method).c_str());
        printer.PrintRaw("        }  // case\n");
    }

    std::string endFunction =
        "        default: {\n"
        "            return ::datasystem::Status(::datasystem::StatusCode::K_UNKNOWN_ERROR,\n"
        "                                        __LINE__, __FILE__, \"Unknown method\");\n"
        "        }\n"
        "    } // switch\n"
        "}\n";
    printer.PrintRaw(endFunction);
}

std::string ZmqRpcGenerator::BuildDirectCallCaseCode(const google::protobuf::MethodDescriptor &method)
{
    if (!HasPayloadSendOption(method) && !HasPayloadRecvOption(method)) {
        return std::string(
            "            auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
            "            auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
            "            if (req == nullptr || rsp == nullptr) {\n"
            "                return ::datasystem::Status(::datasystem::StatusCode::K_RUNTIME_ERROR,\n"
            "                    __LINE__, __FILE__, \"Type mismatch for $methodName$\");\n"
            "            }\n"
            "            return impl_.$methodName$(*req, *rsp);\n");
    }
    // Payload variants: not supported in DirectCallMethod yet
    return std::string(
        "            return ::datasystem::Status(::datasystem::StatusCode::K_NOT_SUPPORTED,\n"
        "                __LINE__, __FILE__, \"DirectCallMethod with payload not yet supported\");\n");
}

// --- Pattern 1: plain (no payloads, no sockets) ---

void ZmqRpcGenerator::ImplementBrpcCallMethodPlain(io::Printer &printer,
                                                   const google::protobuf::MethodDescriptor &method,
                                                   int methodIndex,
                                                   const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    std::string impl =
        "$indent$auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
        "$indent$auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
        "$indent$if (req == nullptr || rsp == nullptr) {\n"
        "$indent$    cntl->SetFailed(\"Request/response type mismatch for $methodName$\");\n"
        "$indent$    return;\n"
        "$indent$}\n"
        "$indent$::datasystem::Status st = impl_.$methodName$(*req, *rsp);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$}\n";
    printer.Print(vars, impl.c_str());
}

// --- Pattern 2: send_payload ---

void ZmqRpcGenerator::ImplementBrpcCallMethodSendPayload(io::Printer &printer,
                                                         const google::protobuf::MethodDescriptor &method,
                                                         int methodIndex,
                                                         const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    // Wire format in IOBuf: [int64_t count][int64_t size1][data1][int64_t size2][data2]...
    // The brpc client stub writes payload in this same framing format.
    std::string impl =
        "$indent$auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
        "$indent$auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
        "$indent$if (req == nullptr || rsp == nullptr) {\n"
        "$indent$    cntl->SetFailed(\"Request/response type mismatch for $methodName$\");\n"
        "$indent$    return;\n"
        "$indent$}\n"
        "$indent$std::vector<::datasystem::RpcMessage> payload;\n"
        "$indent$butil::IOBuf &attachment = cntl->request_attachment();\n"
        "$indent$do {\n"
        "$indent$    if (attachment.empty()) { break; }\n"
        "$indent$    int64_t count = 0;\n"
        "$indent$    if (attachment.copy_to(reinterpret_cast<void*>(&count), sizeof(count)) != sizeof(count)) "
        "{ break; }\n"
        "$indent$    attachment.pop_front(sizeof(count));\n"
        "$indent$    payload.resize(static_cast<size_t>(count));\n"
        "$indent$    for (auto& msg : payload) {\n"
        "$indent$        int64_t sz = 0;\n"
        "$indent$        if (attachment.copy_to(reinterpret_cast<void*>(&sz), sizeof(sz)) != sizeof(sz)) { break; }\n"
        "$indent$        attachment.pop_front(sizeof(sz));\n"
        "$indent$        if (msg.Resize(static_cast<size_t>(sz)).IsError()) { break; }\n"
        "$indent$        if (attachment.copy_to(msg.Data(), static_cast<size_t>(sz)) != static_cast<size_t>(sz)) "
        "{ break; }\n"
        "$indent$        attachment.pop_front(static_cast<size_t>(sz));\n"
        "$indent$    }\n"
        "$indent$} while (false);\n"
        "$indent$::datasystem::Status st = impl_.$methodName$(*req, *rsp, std::move(payload));\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$}\n";
    printer.Print(vars, impl.c_str());
}

// --- Pattern 3: recv_payload ---

void ZmqRpcGenerator::ImplementBrpcCallMethodRecvPayload(io::Printer &printer,
                                                         const google::protobuf::MethodDescriptor &method,
                                                         int methodIndex,
                                                         const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    // Wire format in IOBuf: [int64_t count][int64_t size1][data1][int64_t size2][data2]...
    std::string impl =
        "$indent$auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
        "$indent$auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
        "$indent$if (req == nullptr || rsp == nullptr) {\n"
        "$indent$    cntl->SetFailed(\"Request/response type mismatch for $methodName$\");\n"
        "$indent$    return;\n"
        "$indent$}\n"
        "$indent$std::vector<::datasystem::RpcMessage> outPayload;\n"
        "$indent$::datasystem::Status st = impl_.$methodName$(*req, *rsp, outPayload);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$} else {\n"
        "$indent$    auto& buf = cntl->response_attachment();\n"
        "$indent$    int64_t count = static_cast<int64_t>(outPayload.size());\n"
        "$indent$    buf.append(reinterpret_cast<const void*>(&count), sizeof(count));\n"
        "$indent$    for (auto& msg : outPayload) {\n"
        "$indent$        int64_t sz = static_cast<int64_t>(msg.Size());\n"
        "$indent$        buf.append(reinterpret_cast<const void*>(&sz), sizeof(sz));\n"
        "$indent$        buf.append(msg.Data(), msg.Size());\n"
        "$indent$    }\n"
        "$indent$}\n";
    printer.Print(vars, impl.c_str());
}

// --- Pattern 2+3 combined: send_payload + recv_payload ---

void ZmqRpcGenerator::ImplementBrpcCallMethodSendRecvPayload(io::Printer &printer,
                                                             const google::protobuf::MethodDescriptor &method,
                                                             int methodIndex,
                                                             const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    // Wire format in IOBuf: [int64_t count][int64_t size1][data1][int64_t size2][data2]...
    std::string impl = BuildSendRecvPayloadImpl();
    printer.Print(vars, impl.c_str());
}

std::string ZmqRpcGenerator::BuildSendRecvPayloadImpl()
{
    return
        "$indent$auto* req = dynamic_cast<const $inputTypeName$*>(request);\n"
        "$indent$auto* rsp = dynamic_cast<$outputTypeName$*>(response);\n"
        "$indent$if (req == nullptr || rsp == nullptr) {\n"
        "$indent$    cntl->SetFailed(\"Request/response type mismatch for $methodName$\");\n"
        "$indent$    return;\n"
        "$indent$}\n"
        "$indent$std::vector<::datasystem::RpcMessage> payload;\n"
        "$indent$std::vector<::datasystem::RpcMessage> outPayload;\n"
        "$indent$// Deserialize request_attachment -> payload\n"
        "$indent$butil::IOBuf &reqBuf = cntl->request_attachment();\n"
        "$indent$do {\n"
        "$indent$    if (reqBuf.empty()) { break; }\n"
        "$indent$    int64_t count = 0;\n"
        "$indent$    if (reqBuf.copy_to(reinterpret_cast<void*>(&count), sizeof(count)) != sizeof(count)) { break; }\n"
        "$indent$    reqBuf.pop_front(sizeof(count));\n"
        "$indent$    payload.resize(static_cast<size_t>(count));\n"
        "$indent$    for (auto& msg : payload) {\n"
        "$indent$        int64_t sz = 0;\n"
        "$indent$        if (reqBuf.copy_to(reinterpret_cast<void*>(&sz), sizeof(sz)) != sizeof(sz)) { break; }\n"
        "$indent$        reqBuf.pop_front(sizeof(sz));\n"
        "$indent$        if (msg.Resize(static_cast<size_t>(sz)).IsError()) { break; }\n"
        "$indent$        if (reqBuf.copy_to(msg.Data(), static_cast<size_t>(sz)) != static_cast<size_t>(sz)) "
        "{ break; }\n"
        "$indent$        reqBuf.pop_front(static_cast<size_t>(sz));\n"
        "$indent$    }\n"
        "$indent$} while (false);\n"
        "$indent$::datasystem::Status st = impl_.$methodName$(*req, *rsp, std::move(payload), outPayload);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$} else {\n"
        "$indent$    // Serialize outPayload -> response_attachment\n"
        "$indent$    auto& rspBuf = cntl->response_attachment();\n"
        "$indent$    int64_t count = static_cast<int64_t>(outPayload.size());\n"
        "$indent$    rspBuf.append(reinterpret_cast<const void*>(&count), sizeof(count));\n"
        "$indent$    for (auto& msg : outPayload) {\n"
        "$indent$        int64_t sz = static_cast<int64_t>(msg.Size());\n"
        "$indent$        rspBuf.append(reinterpret_cast<const void*>(&sz), sizeof(sz));\n"
        "$indent$        rspBuf.append(msg.Data(), msg.Size());\n"
        "$indent$    }\n"
        "$indent$}\n";
}

// --- Pattern 4: unary_socket ---

void ZmqRpcGenerator::ImplementBrpcCallMethodUnarySocket(io::Printer &printer,
                                                         const google::protobuf::MethodDescriptor &method,
                                                         int methodIndex,
                                                         const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    std::string impl =
        "$indent$// UnarySocket pattern: async completion via done closure.\n"
        "$indent$// Release done from ClosureGuard so serverApi owns it.\n"
        "$indent$google::protobuf::Closure* asyncDone = done_guard.release();\n"
        "$indent$auto serverApi =\n"
        "$indent$    std::make_shared<::datasystem::BrpcServerUnaryWriterReader<$outputTypeName$, $inputTypeName$>>(\n"
        "$indent$        cntl, request, response, asyncDone);\n";
    if (HasPayloadRecvOption(method)) {
        impl +=
        "$indent$// Defer done_->Run() so SendPayload()/SendAndTagPayload() can write\n"
        "$indent$// payload to response_attachment before brpc serializes the response.\n"
        "$indent$serverApi->SetHasRecvPayload(true);\n";
    }
    impl += BuildScTimeoutDurationInitSnippet();
    impl +=
        "$indent$::datasystem::Status st = impl_.$methodName$(serverApi);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$    // Mark done as consumed so ~BrpcServerUnaryWriterReader does not double-close.\n"
        "$indent$    serverApi->MarkDoneConsumed();\n"
        "$indent$    // Run done to send the error response.\n"
        "$indent$    if (asyncDone) { asyncDone->Run(); }\n"
        "$indent$}\n"
        "$indent$// If st.IsOk(), done->Run() will be called by Write()/SendStatus()\n"
        "$indent$// (or by SendPayload()/SendAndTagPayload() when SetHasRecvPayload(true)).\n"
        "$indent$// Falls back to ~BrpcServerUnaryWriterReader() if none are called.\n";
    printer.Print(vars, impl.c_str());
}

std::string ZmqRpcGenerator::BuildScTimeoutDurationInitSnippet()
{
    return
        "$indent$// Initialize scTimeoutDuration from brpc deadline, matching ZMQ behavior.\n"
        "$indent$// NOTE (F07): scTimeoutDuration is thread_local. Under brpc bthread M:N\n"
        "$indent$// scheduling, the bthread handling this RPC may migrate to a different\n"
        "$indent$// pthread across yield points (e.g. master->worker sub-RPCs), so reads of\n"
        "$indent$// scTimeoutDuration from service impls after such yields may land on a\n"
        "$indent$// different pthread-local copy. Downstream service impls that depend on\n"
        "$indent$// scTimeoutDuration.CalcRealRemainingTime() after yields must re-Init() it\n"
        "$indent$// themselves (as master_sc_service_impl.cpp already does). A full fix\n"
        "$indent$// requires moving scTimeoutDuration off thread_local (bthread-local or\n"
        "$indent$// Controller-carried); tracked as follow-up, not done here to avoid\n"
        "$indent$// touching all service files.\n"
        "$indent${\n"
        "$indent$    int64_t deadlineUs = cntl->deadline_us();\n"
        "$indent$    if (deadlineUs > 0) {\n"
        "$indent$        struct timeval tv;\n"
        "$indent$        gettimeofday(&tv, nullptr);\n"
        "$indent$        int64_t nowUs = static_cast<int64_t>(tv.tv_sec) * 1000000L + tv.tv_usec;\n"
        "$indent$        // Round up (F17): integer truncation would turn (0, 999us] into 0ms,\n"
        "$indent$        // causing scTimeoutDuration.Init() with default (infinite) timeout.\n"
        "$indent$        int64_t remainingMs = (deadlineUs - nowUs + 999) / 1000;\n"
        "$indent$        if (remainingMs > 0) {\n"
        "$indent$            scTimeoutDuration.Init(remainingMs);\n"
        "$indent$        } else {\n"
        "$indent$            scTimeoutDuration.Init();\n"
        "$indent$        }\n"
        "$indent$    } else {\n"
        "$indent$        scTimeoutDuration.Init();\n"
        "$indent$    }\n"
        "$indent$}\n";
}

// --- Streaming patterns (full brpc streaming integration pending) ---

void ZmqRpcGenerator::ImplementBrpcCallMethodClientStream(io::Printer &printer,
                                                          const google::protobuf::MethodDescriptor &method,
                                                          int methodIndex,
                                                          const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    std::string impl =
        "$indent$// brpc client-streaming (pending implementation)\n"
        "$indent$// Method: $methodName$(ServerReader<$inputTypeName$>, $outputTypeName$ &)\n"
        "$indent$cntl->SetFailed(\"Client-streaming not yet supported in brpc adapter\");\n";
    printer.Print(vars, impl.c_str());
}

void ZmqRpcGenerator::ImplementBrpcCallMethodServerStream(io::Printer &printer,
                                                          const google::protobuf::MethodDescriptor &method,
                                                          int methodIndex,
                                                          const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    std::string impl =
        "$indent$// brpc server-streaming (pending implementation)\n"
        "$indent$// Method: $methodName$(ServerWriter<$outputTypeName$>, $inputTypeName$ &)\n"
        "$indent$cntl->SetFailed(\"Server-streaming not yet supported in brpc adapter\");\n";
    printer.Print(vars, impl.c_str());
}

void ZmqRpcGenerator::ImplementBrpcCallMethodBidiStream(io::Printer &printer,
                                                        const google::protobuf::MethodDescriptor &method,
                                                        int methodIndex,
                                                        const std::string &indent)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["indent"] = indent;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    // Bidi-streaming pattern: create BrpcServerWriterReaderImpl wrapper
    // The service implementation reads the request from RPC body and writes
    // N responses via brpc::StreamWrite through the ServerWriterReaderBase interface.
    std::string impl =
        "$indent$// Bidi-streaming via BrpcServerWriterReaderImpl\n"
        "$indent$auto brpcStreamImpl =\n"
        "$indent$    std::make_unique<::datasystem::BrpcServerWriterReaderImpl<$outputTypeName$, $inputTypeName$>>(\n"
        "$indent$        cntl, request);\n"
        "$indent$auto stream =\n"
        "$indent$    std::make_shared<::datasystem::ServerWriterReader<$outputTypeName$, $inputTypeName$>>("
        "std::move(brpcStreamImpl));\n"
        "$indent$::datasystem::Status st = impl_.$methodName$(stream);\n"
        "$indent$if (st.IsError()) {\n"
        "$indent$    cntl->SetFailed(st.GetMsg() + \"\\x01DS_ERR:\" + "
        "std::to_string(static_cast<int>(st.GetCode())) + \"\\x02\");\n"
        "$indent$}\n";
    printer.Print(vars, impl.c_str());
}

}  // namespace datasystem
