/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2022. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Description: Brpc client stub generator (V8).
 * Generates {ServiceName}_BrpcStub and {ServiceName}_BrpcGenericStub classes
 * that use brpc::Channel to call a brpc server.
 */
#include "datasystem/common/rpc/plugin_generator/rpc_generator.h"

#include <google/protobuf/descriptor.h>

namespace datasystem {

// ============================================================================
// Brpc client stub header
// ============================================================================

void RpcGenerator::CreateBrpcStubHeader(const google::protobuf::FileDescriptor &file,
                                        compiler::GeneratorContext *generatorCtx) const
{
    std::unique_ptr<io::ZeroCopyOutputStream> outputFile(generatorCtx->Open(fileName + ".brpc.stub.pb.h"));
    io::Printer printer(outputFile.get(), '$');

    GenerateBrpcStubPrologue(printer, file);
    printer.PrintRaw(namespaceBegin);

    for (auto i = 0; i < file.service_count(); ++i) {
        auto *svc = file.service(i);
        GenerateBrpcStubClass(printer, *svc, PREFIX);
        GenerateBrpcGenericStubClass(printer, *svc, PREFIX);
    }

    printer.PrintRaw(namespaceEnd);
    printer.PrintRaw(ENDIF);
}

void RpcGenerator::GenerateBrpcStubPrologue(io::Printer &printer,
                                            const google::protobuf::FileDescriptor &file) const
{
    std::map<std::string, std::string> vars;
    vars["full_file_name"] = file.name();
    vars["file_name"] = fileName;
    std::string fileNameHeader = fileName;
    std::replace(fileNameHeader.begin(), fileNameHeader.end(), '/', '_');
    vars["file_name_header"] = fileNameHeader;
    std::string impl =
        "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
        "// source: $full_file_name$\n"
        "#ifndef DATASYSTEM_PROTO_BRPC_$file_name_header$_STUB_H\n"
        "#define DATASYSTEM_PROTO_BRPC_$file_name_header$_STUB_H\n"
        "#include <memory>\n"
        "#include <string>\n"
        "#include <vector>\n";
    if (file.message_type_count() > 0) {
        impl += "#include \"$file_name$.pb.h\"\n";
    }
    impl +=
        "#include <brpc/channel.h>\n"
        "#include <google/protobuf/descriptor.h>\n"
        "#include \"datasystem/common/rpc/brpc_async_context.h\"\n"
        "#include \"datasystem/common/rpc/brpc_client_unary_writer_reader.h\"\n"
        "#include \"datasystem/common/rpc/brpc_client_stream_writer_reader.h\"\n"
        "#include \"datasystem/common/rpc/brpc_client_stream_impl.h\"\n"
        "#include \"datasystem/common/rpc/brpc_status_util.h\"\n"
        "#include \"datasystem/common/rpc/rpc_message.h\"\n"
        "#include \"datasystem/common/rpc/rpc_options.h\"\n"
        "#include \"datasystem/common/rpc/rpc_stub_base.h\"\n"
        "#include \"datasystem/common/rpc/rpc_unary_client_impl.h\"\n"
        "#include \"datasystem/utils/status.h\"\n";
    printer.Print(vars, impl.c_str());
    for (auto k = 0; k < file.dependency_count(); ++k) {
        auto depend = file.dependency(k)->name();
        bool isAProto = StripSuffix(depend, ".proto");
        if (isAProto) {
            vars["depend"] = depend;
            printer.Print(vars, "#include \"$depend$.pb.h\"\n");
        }
    }
}

void RpcGenerator::GenerateBrpcStubClass(io::Printer &printer, const google::protobuf::ServiceDescriptor &svc,
                                         const std::string &indent) const
{
    (void)indent;
    const std::string &svcName = svc.name();
    std::map<std::string, std::string> vars;
    vars["svc_name_string"] = "\"" + svcName + "\"";
    vars["stub"] = svcName + "_BrpcStub";
    vars["full_svc_name"] = packageName.empty() ? svcName : packageName + "." + svcName;

    const std::string constructor =
        "class $stub$ {\n"
        "public:\n"
        "    explicit $stub$(brpc::Channel *channel, int32_t timeoutMs = -1)\n"
        "        : channel_(channel), timeoutMs_(timeoutMs)\n"
        "        , svcDesc_(::google::protobuf::DescriptorPool::generated_pool()\n"
        "              ->FindServiceByName(\"$full_svc_name$\")) {}\n"
        "    ~$stub$() = default;\n"
        "    static std::string FullServiceName() { return \"$full_svc_name$\"; }\n"
        "    static std::string ServiceName() { return $svc_name_string$; }\n"
        "    ::datasystem::Status GetInitStatus() const {\n"
        "        if (channel_ == nullptr) {\n"
        "            return ::datasystem::Status(::datasystem::StatusCode::K_NOT_READY,\n"
        "                                        __LINE__, __FILE__, \"brpc channel is null\");\n"
        "        }\n"
        "        if (svcDesc_ == nullptr) {\n"
        "            return ::datasystem::Status(::datasystem::StatusCode::K_NOT_READY,\n"
        "                                        __LINE__, __FILE__, \"service descriptor not found\");\n"
        "        }\n"
        "        return ::datasystem::Status::OK();\n"
        "    }\n";
    printer.Print(vars, constructor.c_str());

    // Implement stub api declarations (same signatures as ZMQ path).
    ImplementStubApiDecl(printer, svc, indent);

    // Add ForgetRequest so GenericStub can delegate to it.
    printer.PrintRaw("    void ForgetRequest(int64_t tagId) {\n"
                     "        asyncCtx_.ForgetCall(tagId);\n"
                     "    }\n");

    // P5 7.3: per-stub liveness probe used by GenericStub delegation.
    printer.PrintRaw("    bool IsPeerAlive(uint32_t threshold) {\n"
                     "        (void)threshold;\n"
                     "        return channel_ != nullptr;\n"
                     "    }\n");

    printer.PrintRaw("private:\n    brpc::Channel *channel_;\n    int32_t timeoutMs_;\n"
                     "    const ::google::protobuf::ServiceDescriptor *svcDesc_;\n"
                     "    ::datasystem::BrpcAsyncContext asyncCtx_;\n};\n");
}

void RpcGenerator::GenerateBrpcGenericStubClass(io::Printer &printer,
                                                const google::protobuf::ServiceDescriptor &svc,
                                                const std::string &indent) const
{
    (void)indent;
    const std::string &svcName = svc.name();
    std::map<std::string, std::string> vars;
    vars["svc_name"] = svcName;
    vars["stub"] = svcName + "_BrpcGenericStub";

    const std::string constructor =
        "class $stub$ : public RpcStubBase {\n"
        "public:\n"
        "    explicit $stub$(brpc::Channel *channel, int32_t timeoutMs = -1);\n"
        "    ~$stub$() = default;\n"
        "    Status GetInitStatus() override;\n";
    printer.Print(vars, constructor.c_str());

    GenerateSvcName(printer, svcName, indent, false);

    ImplementStubApiDecl(printer, svc, indent);

    ImplementGenericStubOtherFuncDecl(printer);

    const std::string impl =
        "private:\n"
        "    std::unique_ptr<$svc_name$_BrpcStub> stub_;\n"
        "};\n";
    printer.Print(vars, impl.c_str());
}

// ============================================================================
// Brpc client stub cpp
// ============================================================================

void RpcGenerator::CreateBrpcStubCpp(const google::protobuf::FileDescriptor &file,
                                     compiler::GeneratorContext *generatorCtx) const
{
    std::unique_ptr<io::ZeroCopyOutputStream> outputFile(generatorCtx->Open(fileName + ".brpc.stub.pb.cc"));
    io::Printer printer(outputFile.get(), '$');

    GenerateBrpcStubCppPrologue(printer, file);
    printer.PrintRaw(namespaceBegin);

    for (auto i = 0; i < file.service_count(); ++i) {
        auto *svc = file.service(i);
        const std::string &svcName = svc->name();
        const std::string stub = svcName + "_BrpcStub";
        ImplementBrpcGenericStubApiDef(printer, *svc, PREFIX);
        ImplementBrpcStubApiDef(printer, *svc, PREFIX);
    }

    printer.PrintRaw(namespaceEnd);
}

void RpcGenerator::GenerateBrpcStubCppPrologue(io::Printer &printer,
                                               const google::protobuf::FileDescriptor &file) const
{
    std::map<std::string, std::string> vars;
    vars["full_file_name"] = file.name();
    vars["file_name"] = fileName;

    std::string impl =
        "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
        "// source: $full_file_name$\n"
        "#include \"$file_name$.brpc.stub.pb.h\"\n"
        "#include <brpc/controller.h>\n";
    printer.Print(vars, impl.c_str());
}

// ============================================================================
// Generic stub implementation (delegates to inner BrpcStub)
// ============================================================================

void RpcGenerator::ImplementBrpcGenericStubApiDef(io::Printer &printer,
                                                  const google::protobuf::ServiceDescriptor &svc,
                                                  const std::string &indent)
{
    (void)indent;
    const std::string &svcName = svc.name();
    ImplementBrpcGenericStubConstructor(printer, svc, indent);
    const std::string stub = svcName + "_BrpcGenericStub";
    ImplementBrpcGenericStubOtherFuncDef(printer, stub);
    for (auto j = 0; j < svc.method_count(); ++j) {
        if (svc.method(j) == nullptr) {
            continue;
        }
        auto &method = *(svc.method(j));
        if (method.client_streaming() && method.server_streaming()) {
            ImplementBrpcGenericStubStreamingDef(printer, method, indent, stub);
        } else if (method.client_streaming() && !method.server_streaming()) {
            ImplementBrpcGenericStubClientStreamingDef(printer, method, indent, stub);
        } else if (!method.client_streaming() && method.server_streaming()) {
            ImplementBrpcGenericStubServerStreamingDef(printer, method, indent, stub);
        } else {
            ImplementBrpcGenericStubAsyncWriteDef(printer, method, indent, stub);
            ImplementBrpcGenericStubAsyncReadDef(printer, method, indent, stub);
            ImplementBrpcGenericStubNoStreamDef(printer, method, indent, stub);
            ImplementBrpcGenericStubNoStreamDef2(printer, method, indent, stub);
            ImplBrpcGenericStubNoStreamShortDef(printer, method, indent, stub);
        }
    }
}

void RpcGenerator::ImplementBrpcGenericStubConstructor(io::Printer &printer,
                                                       const google::protobuf::ServiceDescriptor &svc,
                                                       const std::string &indent)
{
    (void)indent;
    const std::string &svcName = svc.name();
    const std::string stub = svcName + "_BrpcGenericStub";
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["svcName"] = svcName;
    std::string impl =
        "$stub$::$stub$(brpc::Channel *channel, int32_t timeoutMs) {\n"
        "    stub_ = std::make_unique<$svcName$_BrpcStub>(channel, timeoutMs);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

void RpcGenerator::ImplementBrpcGenericStubOtherFuncDef(io::Printer &printer, const std::string &stub)
{
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    const std::string forgetRequest =
        "void $stub$::ForgetRequest(int64_t tagId) {\n"
        "    stub_->ForgetRequest(tagId);\n"
        "}\n";
    const std::string isPeerAlive =
        "bool $stub$::IsPeerAlive(uint32_t threshold) {\n"
        "    (void)threshold;\n"
        "    return stub_->IsPeerAlive(threshold);\n"
        "}\n";
    const std::string cacheSession =
        "void $stub$::CacheSession(bool cache) {\n"
        "    (void)cache;\n"
        "    // brpc channels are persistent, no-op\n"
        "}\n";
    const std::string getInitStatus =
        "Status $stub$::GetInitStatus() {\n"
        "    return stub_->GetInitStatus();\n"
        "}\n";
    const std::string setExclusiveConnInfo =
        "void $stub$::SetExclusiveConnInfo(const std::optional<int32_t> &exclusiveId,\n"
        "                                   const std::string &sockPath) {\n"
        "    (void)exclusiveId;\n"
        "    (void)sockPath;\n"
        "    // brpc does not support exclusive connections, no-op\n"
        "}\n";
    printer.Print(vars, forgetRequest.c_str());
    printer.Print(vars, isPeerAlive.c_str());
    printer.Print(vars, cacheSession.c_str());
    printer.Print(vars, getInitStatus.c_str());
    printer.Print(vars, setExclusiveConnInfo.c_str());
}

// ============================================================================
// BrpcStub inner implementation (direct brpc::Channel calls)
// ============================================================================

void RpcGenerator::ImplementBrpcStubApiDef(io::Printer &printer,
                                           const google::protobuf::ServiceDescriptor &svc,
                                           const std::string &indent)
{
    (void)indent;
    const std::string &svcName = svc.name();
    const std::string stub = svcName + "_BrpcStub";
    for (auto j = 0; j < svc.method_count(); ++j) {
        if (svc.method(j) == nullptr) {
            continue;
        }
        auto &method = *(svc.method(j));
        if (method.client_streaming() && method.server_streaming()) {
            ImplementBrpcStubStreamingDef(printer, method, j, indent, stub);
        } else if (method.client_streaming() && !method.server_streaming()) {
            ImplementBrpcStubClientStreamingDef(printer, method, j, indent, stub);
        } else if (!method.client_streaming() && method.server_streaming()) {
            ImplementBrpcStubServerStreamingDef(printer, method, j, indent, stub);
        } else {
            ImplementBrpcStubAsyncWriteDef(printer, method, j, indent, stub);
            ImplementBrpcStubAsyncReadDef(printer, method, j, indent, stub);
            ImplementBrpcStubNoStreamDef(printer, method, j, indent, stub);
            ImplementBrpcStubNoStreamDef2(printer, method, j, indent, stub);
            ImplBrpcStubNoStreamShortDef(printer, method, j, indent, stub);
        }
    }
}

// --- Plain unary (no payloads, no sockets) ---

void RpcGenerator::ImplementBrpcStubNoStreamDef(io::Printer &printer,
                                                const google::protobuf::MethodDescriptor &method,
                                                int methodIndex,
                                                const std::string &indent,
                                                const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["methodIndex"] = std::to_string(methodIndex);
    vars["optSendPayload1"] = HasPayloadSendOption(method)
        ? ", const std::vector<::datasystem::MemView> &payload" : "";
    vars["optRecvPayload1"] = HasPayloadRecvOption(method)
        ? ", std::vector<::datasystem::RpcMessage> &recvBuffer" : "";

    std::string impl =
        "::datasystem::Status $stub$::$methodName$(const ::datasystem::RpcOptions &opt,\n"
        "                                          const $inputTypeName$& rq,\n"
        "                                          $outputTypeName$& reply"
        "$optSendPayload1$$optRecvPayload1$) {\n"
        "    brpc::Controller cntl;\n"
        "    if (timeoutMs_ > 0) {\n"
        "        cntl.set_timeout_ms(timeoutMs_);\n"
        "    }\n"
        "    auto overrideMs = opt.GetTimeout();\n"
        "    if (overrideMs > 0) {\n"
        "        cntl.set_timeout_ms(overrideMs);\n"
        "    }\n";
    if (HasPayloadSendOption(method)) {
        impl += BuildSendPayloadFramingSnippet();
    }
    impl +=
        "    channel_->CallMethod(svcDesc_->method($methodIndex$),\n"
        "                         &cntl, &rq, &reply, nullptr);\n";
    if (HasPayloadRecvOption(method)) {
        impl += BuildRecvPayloadFramingSnippet();
    }
    impl +=
        "    if (cntl.Failed()) {\n"
        "        ::datasystem::Status embedded = ::datasystem::TryExtractStatusFromResponse(reply);\n"
        "        if (embedded.IsError()) {\n"
        "            return embedded;\n"
        "        }\n"
        "        // brpc ErrorCode() uses its own namespace (EXyz); server app\n"
        "        // error codes are in the text as \\x01DS_ERR:N\\x02 sentinel.\n"
        "        return ::datasystem::TryExtractStatusFromControllerError(cntl.ErrorText());\n"
        "    }\n"
        "    return ::datasystem::Status::OK();\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

std::string RpcGenerator::BuildSendPayloadFramingSnippet()
{
    return
        "    // Write send payload to request attachment with framing\n"
        "    // Wire format: [int64_t count][int64_t size1][data1][int64_t size2][data2]...\n"
        "    auto& reqBuf = cntl.request_attachment();\n"
        "    int64_t count = static_cast<int64_t>(payload.size());\n"
        "    reqBuf.append(reinterpret_cast<const void*>(&count), sizeof(count));\n"
        "    for (const auto &buf : payload) {\n"
        "        int64_t sz = static_cast<int64_t>(buf.Size());\n"
        "        reqBuf.append(reinterpret_cast<const void*>(&sz), sizeof(sz));\n"
        "        reqBuf.append(buf.Data(), buf.Size());\n"
        "    }\n";
}

std::string RpcGenerator::BuildRecvPayloadFramingSnippet()
{
    return
        "    // Deserialize recv payload from response attachment\n"
        "    // Wire format: [int64_t count][int64_t size1][data1][int64_t size2][data2]...\n"
        "    butil::IOBuf &rspBuf = cntl.response_attachment();\n"
        "    recvBuffer.clear();\n"
        "    do {\n"
        "        if (rspBuf.empty()) { break; }\n"
        "        int64_t count = 0;\n"
        "        if (rspBuf.copy_to(reinterpret_cast<void*>(&count), sizeof(count)) != sizeof(count)) { break; }\n"
        "        rspBuf.pop_front(sizeof(count));\n"
        "        recvBuffer.resize(static_cast<size_t>(count));\n"
        "        for (auto& msg : recvBuffer) {\n"
        "            int64_t sz = 0;\n"
        "            if (rspBuf.copy_to(reinterpret_cast<void*>(&sz), sizeof(sz)) != sizeof(sz)) { break; }\n"
        "            rspBuf.pop_front(sizeof(sz));\n"
        "            if (msg.Resize(static_cast<size_t>(sz)).IsError()) { break; }\n"
        "            if (rspBuf.copy_to(msg.Data(), static_cast<size_t>(sz)) != static_cast<size_t>(sz)) { break; }\n"
        "            rspBuf.pop_front(static_cast<size_t>(sz));\n"
        "        }\n"
        "    } while (false);\n";
}

// --- Unary variant 2: returns ClientUnaryWriterReader wrapper ---

void RpcGenerator::ImplementBrpcStubNoStreamDef2(io::Printer &printer,
                                                 const google::protobuf::MethodDescriptor &method,
                                                 int methodIndex,
                                                 const std::string &indent,
                                                 const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["methodIndex"] = std::to_string(methodIndex);

    std::string impl =
        "::datasystem::Status $stub$::$methodName$(const ::datasystem::RpcOptions &opt,\n"
        "// F05 note: client reader template is <Request, Response> (input first).\n"
        "// Server reader (brpc_service_generator.cpp) is intentionally <Response, Request>\n"
        "// (output first) to match each side's natural arg ordering — Request->Response\n"
        "// for the caller, Response<-Request for the handler. Do NOT unify without\n"
        "// changing both reader class definitions.\n"
        "\t\tstd::unique_ptr<datasystem::ClientUnaryWriterReader<$inputTypeName$, $outputTypeName$>> *out) {\n"
        "    int32_t tmo = timeoutMs_;\n"
        "    if (opt.GetTimeout() > 0) { tmo = opt.GetTimeout(); }\n"
        "    auto brpcImpl =\n"
        "        std::make_unique<datasystem::BrpcClientUnaryWriterReader<$inputTypeName$, $outputTypeName$>>(\n"
        "            channel_, svcDesc_->method($methodIndex$), tmo);\n"
        "    *out = std::make_unique<datasystem::ClientUnaryWriterReader<$inputTypeName$, "
        "$outputTypeName$>>(std::move(brpcImpl));\n"
        "    return ::datasystem::Status::OK();\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

// --- Short convenience wrapper ---

void RpcGenerator::ImplBrpcStubNoStreamShortDef(io::Printer &printer,
                                                const google::protobuf::MethodDescriptor &method,
                                                int methodIndex,
                                                const std::string &indent,
                                                const std::string &stub)
{
    (void)methodIndex;
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["optSendPayload1"] = HasPayloadSendOption(method)
        ? ", const std::vector<::datasystem::MemView> &payload" : "";
    vars["optRecvPayload1"] = HasPayloadRecvOption(method)
        ? ", std::vector<::datasystem::RpcMessage> &recvBuffer" : "";
    vars["optSendPayload2"] = HasPayloadSendOption(method) ? ", payload" : "";
    vars["optRecvPayload2"] = HasPayloadRecvOption(method) ? ", recvBuffer" : "";

    std::string impl =
        "::datasystem::Status $stub$::$methodName$(const $inputTypeName$& rq,\n"
        "                                          $outputTypeName$& reply"
        "$optSendPayload1$$optRecvPayload1$) {\n"
        "    return $methodName$(::datasystem::RpcOptions(), rq, reply$optSendPayload2$$optRecvPayload2$);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

// --- Async write ---

void RpcGenerator::ImplementBrpcStubAsyncWriteDef(io::Printer &printer,
                                                  const google::protobuf::MethodDescriptor &method,
                                                  int methodIndex,
                                                  const std::string &indent,
                                                  const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["methodIndex"] = std::to_string(methodIndex);
    vars["optSendPayload1"] = HasPayloadSendOption(method)
        ? ", const std::vector<::datasystem::MemView> &payload" : "";
    vars["optSendPayload2"] = HasPayloadSendOption(method) ? ", payload" : "";

    std::string impl = BuildAsyncWriteImpl(method);
    printer.Print(vars, impl.c_str());
}

std::string RpcGenerator::BuildAsyncWriteImpl(const google::protobuf::MethodDescriptor &method)
{
    // AsyncWrite: allocate a tag, issue CallMethod with a Done closure, return immediately.
    // The response and controller live inside BrpcAsyncCall, owned by asyncCtx_ via shared_ptr.
    // The Done closure signals a per-call cv when brpc completes the RPC on a bthread.
    std::string impl =
        "::datasystem::Status $stub$::$methodName$AsyncWrite(const ::datasystem::RpcOptions &opt,\n"
        "    const $inputTypeName$& rq, int64_t &tagId$optSendPayload1$) {\n"
        "    tagId = asyncCtx_.AllocateTag();\n"
        "    auto call = asyncCtx_.GetCall(tagId);\n"
        "    if (call == nullptr) {\n"
        "        return ::datasystem::Status(::datasystem::StatusCode::K_RUNTIME_ERROR,\n"
        "            __LINE__, __FILE__, \"Failed to allocate async call tag\");\n"
        "    }\n"
        "    if (timeoutMs_ > 0) {\n"
        "        call->cntl.set_timeout_ms(timeoutMs_);\n"
        "    }\n"
        "    auto overrideMs = opt.GetTimeout();\n"
        "    if (overrideMs > 0) {\n"
        "        call->cntl.set_timeout_ms(overrideMs);\n"
        "    }\n";
    if (HasPayloadSendOption(method)) {
        impl +=
            "    // Framed payload in request attachment (same wire format as sync path)\n"
            "    auto& reqBuf = call->cntl.request_attachment();\n"
            "    int64_t count = static_cast<int64_t>(payload.size());\n"
            "    reqBuf.append(reinterpret_cast<const void*>(&count), sizeof(count));\n"
            "    for (const auto &buf : payload) {\n"
            "        int64_t sz = static_cast<int64_t>(buf.Size());\n"
            "        reqBuf.append(reinterpret_cast<const void*>(&sz), sizeof(sz));\n"
            "        reqBuf.append(buf.Data(), buf.Size());\n"
            "    }\n";
    }
    impl +=
        "    // Heap-allocate response and request so they survive until AsyncRead consumes them.\n"
        "    // Stored in call->response/call->request (unique_ptr) for cleanup in ForgetRequest\n"
        "    // or destructor. Request is explicitly copied because brpc serializes the protobuf\n"
        "    // on a bthread asynchronously; the caller's stack rq would dangle after AsyncWrite\n"
        "    // returns.\n"
        "    call->response = std::make_unique<$outputTypeName$>();\n"
        "    call->request = std::make_unique<$inputTypeName$>(rq);\n"
        "    auto done = asyncCtx_.MakeDone(call);\n"
        "    channel_->CallMethod(svcDesc_->method($methodIndex$),\n"
        "        &call->cntl, call->request.get(), call->response.get(), done);\n"
        "    return ::datasystem::Status::OK();\n"
        "}\n"
        "::datasystem::Status $stub$::$methodName$AsyncWrite(const $inputTypeName$& rq,\n"
        "    int64_t &tagId$optSendPayload1$) {\n"
        "    return $methodName$AsyncWrite(::datasystem::RpcOptions(), rq, tagId$optSendPayload2$);\n"
        "}\n";
    return impl;
}

// --- Async read ---

void RpcGenerator::ImplementBrpcStubAsyncReadDef(io::Printer &printer,
                                                 const google::protobuf::MethodDescriptor &method,
                                                 int methodIndex,
                                                 const std::string &indent,
                                                 const std::string &stub)
{
    (void)indent;
    (void)methodIndex;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["optRecvPayload1"] = HasPayloadRecvOption(method)
        ? ", std::vector<::datasystem::RpcMessage> &recvBuffer" : "";

    std::string impl = BuildAsyncReadImpl(method);
    printer.Print(vars, impl.c_str());
}

std::string RpcGenerator::BuildAsyncReadImpl(const google::protobuf::MethodDescriptor &method)
{
    // AsyncRead: look up tag, wait for RPC completion via cv, copy response, clean up.
    // If flags contains DONTWAIT, returns K_TRY_AGAIN if the RPC hasn't completed yet.
    std::string impl =
        "::datasystem::Status $stub$::$methodName$AsyncRead(int64_t tagId, $outputTypeName$ &reply"
        "$optRecvPayload1$,\n"
        "    ::datasystem::RpcRecvFlags flags) {\n"
        "    // For DONTWAIT: peek first without removing from map.\n"
        "    if (flags == ::datasystem::RpcRecvFlags::DONTWAIT) {\n"
        "        auto call = asyncCtx_.GetCall(tagId);\n"
        "        if (call == nullptr) {\n"
        "            return ::datasystem::Status(::datasystem::StatusCode::K_INVALID,\n"
        "                __LINE__, __FILE__,\n"
        "                \"Tag \" + std::to_string(tagId) + \" not found\");\n"
        "        }\n"
        "        std::lock_guard<std::mutex> lock(call->mtx);\n"
        "        if (!call->completed) {\n"
        "            return ::datasystem::Status(::datasystem::StatusCode::K_TRY_AGAIN,\n"
        "                __LINE__, __FILE__, \"Async RPC not yet completed\");\n"
        "        }\n"
        "    }\n"
        "    // Remove from map. After this the tag is consumed regardless of outcome.\n"
        "    auto call = asyncCtx_.TakeCall(tagId);\n"
        "    if (call == nullptr) {\n"
        "        return ::datasystem::Status(::datasystem::StatusCode::K_INVALID,\n"
        "            __LINE__, __FILE__,\n"
        "            \"Tag \" + std::to_string(tagId) + \" not found\");\n"
        "    }\n"
        "    // Transfer response ownership from call->response unique_ptr.\n"
        "    auto respGuard = std::move(call->response);\n"
        "    auto *typedResp = static_cast<$outputTypeName$*>(respGuard.get());\n"
        "    {\n"
        "        std::unique_lock<std::mutex> lock(call->mtx);\n"
        "        call->cv.wait(lock, [&call] { return call->completed; });\n"
        "    }\n"
        "    if (call->failed) {\n"
        "        ::datasystem::Status embedded = ::datasystem::TryExtractStatusFromResponse(*typedResp);\n"
        "        if (embedded.IsError()) {\n"
        "            return embedded;\n"
        "        }\n"
        "        return ::datasystem::TryExtractStatusFromControllerError(call->errorText);\n"
        "    }\n"
        "    reply.CopyFrom(*typedResp);\n";
    if (HasPayloadRecvOption(method)) {
        impl += BuildAsyncRecvPayloadFramingSnippet();
    }
    impl +=
        "    return ::datasystem::Status::OK();\n"
        "}\n";
    return impl;
}

std::string RpcGenerator::BuildAsyncRecvPayloadFramingSnippet()
{
    return
        "    // Deserialize recv payload from response attachment (same wire format as sync).\n"
        "    // Uses responseAttachment (snapshot taken in OnRpcDone under lock) instead of\n"
        "    // cntl.response_attachment() to avoid lock-free access after Done returns.\n"
        "    butil::IOBuf &rspBuf = call->responseAttachment;\n"
        "    recvBuffer.clear();\n"
        "    do {\n"
        "        if (rspBuf.empty()) { break; }\n"
        "        int64_t count = 0;\n"
        "        if (rspBuf.copy_to(reinterpret_cast<void*>(&count),\n"
        "            sizeof(count)) != sizeof(count)) { break; }\n"
        "        rspBuf.pop_front(sizeof(count));\n"
        "        recvBuffer.resize(static_cast<size_t>(count));\n"
        "        for (auto& msg : recvBuffer) {\n"
        "            int64_t sz = 0;\n"
        "            if (rspBuf.copy_to(reinterpret_cast<void*>(&sz),\n"
        "                sizeof(sz)) != sizeof(sz)) { break; }\n"
        "            rspBuf.pop_front(sizeof(sz));\n"
        "            if (msg.Resize(static_cast<size_t>(sz)).IsError()) { break; }\n"
        "            if (rspBuf.copy_to(msg.Data(), static_cast<size_t>(sz))\n"
        "                != static_cast<size_t>(sz)) { break; }\n"
        "            rspBuf.pop_front(static_cast<size_t>(sz));\n"
        "        }\n"
        "    } while (false);\n";
}

// --- Bidi streaming ---

void RpcGenerator::ImplementBrpcStubStreamingDef(io::Printer &printer,
                                                 const google::protobuf::MethodDescriptor &method,
                                                 int methodIndex,
                                                 const std::string &indent,
                                                 const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["methodIndex"] = std::to_string(methodIndex);

    std::string impl =
        "::datasystem::Status $stub$::$methodName$(\n"
        "    const ::datasystem::RpcOptions &opt,\n"
        "    std::unique_ptr<datasystem::ClientWriterReader<$inputTypeName$, $outputTypeName$>> *out) {\n"
        "    int32_t tmo = timeoutMs_;\n"
        "    if (opt.GetTimeout() > 0) { tmo = opt.GetTimeout(); }\n"
        "    auto brpcImpl =\n"
        "        std::make_unique<datasystem::BrpcClientStreamWriterReader<$inputTypeName$, $outputTypeName$>>(\n"
        "            channel_, svcDesc_->method($methodIndex$), tmo);\n"
        "    *out = std::make_unique<datasystem::ClientWriterReader<$inputTypeName$, "
        "$outputTypeName$>>(std::move(brpcImpl));\n"
        "    return ::datasystem::Status::OK();\n"
        "}\n"
        "::datasystem::Status $stub$::$methodName$(\n"
        "    std::unique_ptr<datasystem::ClientWriterReader<$inputTypeName$, $outputTypeName$>> *out) {\n"
        "    return $methodName$(::datasystem::RpcOptions(), out);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

// --- Client streaming ---

void RpcGenerator::ImplementBrpcStubClientStreamingDef(io::Printer &printer,
                                                       const google::protobuf::MethodDescriptor &method,
                                                       int methodIndex,
                                                       const std::string &indent,
                                                       const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["methodIndex"] = std::to_string(methodIndex);

    // Client-streaming (stream->unary): client writes N messages via
    // BrpcClientWriterImpl, wrapped in ClientWriter.
    std::string impl =
        "::datasystem::Status $stub$::$methodName$(const ::datasystem::RpcOptions &opt,\n"
        "    std::unique_ptr<datasystem::ClientWriter<$inputTypeName$>> *out) {\n"
        "    int32_t tmo = timeoutMs_;\n"
        "    if (opt.GetTimeout() > 0) { tmo = opt.GetTimeout(); }\n"
        "    auto impl = std::make_unique<datasystem::BrpcClientWriterImpl<$inputTypeName$>>(\n"
        "        channel_, svcDesc_->method($methodIndex$), tmo);\n"
        "    *out = std::make_unique<datasystem::ClientWriter<$inputTypeName$>>(std::move(impl));\n"
        "    return ::datasystem::Status::OK();\n"
        "}\n"
        "::datasystem::Status $stub$::$methodName$("
        "std::unique_ptr<datasystem::ClientWriter<$inputTypeName$>> *out) {\n"
        "    return $methodName$(::datasystem::RpcOptions(), out);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

// --- Server streaming ---

void RpcGenerator::ImplementBrpcStubServerStreamingDef(io::Printer &printer,
                                                       const google::protobuf::MethodDescriptor &method,
                                                       int methodIndex,
                                                       const std::string &indent,
                                                       const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["methodIndex"] = std::to_string(methodIndex);
    vars["optSendPayload1"] = HasPayloadSendOption(method)
        ? ", const std::vector<::datasystem::MemView> &payload" : "";
    vars["optSendPayload2"] = HasPayloadSendOption(method) ? ", payload" : "";

    // Server-streaming (unary->stream): client sends request, receives N
    // responses via BrpcClientReaderImpl wrapped in ClientReader.
    std::string impl =
        "::datasystem::Status $stub$::$methodName$(const ::datasystem::RpcOptions &opt,\n"
        "    std::unique_ptr<datasystem::ClientReader<$outputTypeName$>> *out,\n"
        "    const $inputTypeName$& rq$optSendPayload1$) {\n"
        "    int32_t tmo = timeoutMs_;\n"
        "    if (opt.GetTimeout() > 0) { tmo = opt.GetTimeout(); }\n"
        "    auto impl =\n"
        "        std::make_unique<datasystem::BrpcClientReaderImpl<$outputTypeName$>>(\n"
        "            channel_, svcDesc_->method($methodIndex$), tmo);\n"
        "    ::datasystem::Status st = impl->Write(rq);\n"
        "    if (st.IsError()) { return st; }\n"
        "    *out = std::make_unique<datasystem::ClientReader<$outputTypeName$>>(std::move(impl));\n"
        "    return ::datasystem::Status::OK();\n"
        "}\n"
        "::datasystem::Status $stub$::$methodName$("
        "std::unique_ptr<datasystem::ClientReader<$outputTypeName$>> *out,\n"
        "    const $inputTypeName$& rq$optSendPayload1$) {\n"
        "    return $methodName$(::datasystem::RpcOptions(), out, rq$optSendPayload2$);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

// ============================================================================
// Generic stub delegation implementations
// ============================================================================

void RpcGenerator::ImplementBrpcGenericStubNoStreamDef(io::Printer &printer,
                                                       const google::protobuf::MethodDescriptor &method,
                                                       const std::string &indent,
                                                       const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["optSendPayload1"] = HasPayloadSendOption(method)
        ? ", const std::vector<::datasystem::MemView> &payload" : "";
    vars["optRecvPayload1"] = HasPayloadRecvOption(method)
        ? ", std::vector<::datasystem::RpcMessage> &recvBuffer" : "";
    vars["optSendPayload2"] = HasPayloadSendOption(method) ? ", payload" : "";
    vars["optRecvPayload2"] = HasPayloadRecvOption(method) ? ", recvBuffer" : "";

    std::string impl =
        "::datasystem::Status $stub$::$methodName$(const ::datasystem::RpcOptions &opt, const $inputTypeName$& rq,\n"
        "                                          $outputTypeName$& reply"
        "$optSendPayload1$$optRecvPayload1$) {\n"
        "    return stub_->$methodName$(opt, rq, reply$optSendPayload2$$optRecvPayload2$);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

void RpcGenerator::ImplementBrpcGenericStubNoStreamDef2(io::Printer &printer,
                                                        const google::protobuf::MethodDescriptor &method,
                                                        const std::string &indent,
                                                        const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    std::string impl =
        "::datasystem::Status $stub$::$methodName$(const ::datasystem::RpcOptions &opt,\n"
        "// F05 note: client reader template is <Request, Response> (input first).\n"
        "// Server reader (brpc_service_generator.cpp) is intentionally <Response, Request>\n"
        "// (output first) to match each side's natural arg ordering — Request->Response\n"
        "// for the caller, Response<-Request for the handler. Do NOT unify without\n"
        "// changing both reader class definitions.\n"
        "\t\tstd::unique_ptr<datasystem::ClientUnaryWriterReader<$inputTypeName$, $outputTypeName$>> *out) {\n"
        "    return stub_->$methodName$(opt, out);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

void RpcGenerator::ImplBrpcGenericStubNoStreamShortDef(io::Printer &printer,
                                                       const google::protobuf::MethodDescriptor &method,
                                                       const std::string &indent,
                                                       const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["optSendPayload1"] = HasPayloadSendOption(method)
        ? ", const std::vector<::datasystem::MemView> &payload" : "";
    vars["optRecvPayload1"] = HasPayloadRecvOption(method)
        ? ", std::vector<::datasystem::RpcMessage> &recvBuffer" : "";
    vars["optSendPayload2"] = HasPayloadSendOption(method) ? ", payload" : "";
    vars["optRecvPayload2"] = HasPayloadRecvOption(method) ? ", recvBuffer" : "";

    std::string impl =
        "::datasystem::Status $stub$::$methodName$(const $inputTypeName$& rq,\n"
        "                                          $outputTypeName$& reply"
        "$optSendPayload1$$optRecvPayload1$) {\n"
        "    return $methodName$(::datasystem::RpcOptions(), rq, reply$optSendPayload2$$optRecvPayload2$);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

void RpcGenerator::ImplementBrpcGenericStubAsyncWriteDef(io::Printer &printer,
                                                         const google::protobuf::MethodDescriptor &method,
                                                         const std::string &indent,
                                                         const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["optSendPayload1"] = HasPayloadSendOption(method)
        ? ", const std::vector<::datasystem::MemView> &payload" : "";
    vars["optSendPayload2"] = HasPayloadSendOption(method) ? ", payload" : "";

    std::string impl =
        "::datasystem::Status $stub$::$methodName$AsyncWrite(const ::datasystem::RpcOptions &opt,\n"
        "    const $inputTypeName$& rq, int64_t &tagId$optSendPayload1$) {\n"
        "    return stub_->$methodName$AsyncWrite(opt, rq, tagId$optSendPayload2$);\n"
        "}\n"
        "::datasystem::Status $stub$::$methodName$AsyncWrite(const $inputTypeName$& rq,\n"
        "    int64_t &tagId$optSendPayload1$) {\n"
        "    return $methodName$AsyncWrite(::datasystem::RpcOptions(), rq, tagId$optSendPayload2$);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

void RpcGenerator::ImplementBrpcGenericStubAsyncReadDef(io::Printer &printer,
                                                        const google::protobuf::MethodDescriptor &method,
                                                        const std::string &indent,
                                                        const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["optRecvPayload1"] = HasPayloadRecvOption(method)
        ? ", std::vector<::datasystem::RpcMessage> &recvBuffer" : "";
    vars["optRecvPayload2"] = HasPayloadRecvOption(method) ? ", recvBuffer" : "";

    std::string impl =
        "::datasystem::Status $stub$::$methodName$AsyncRead(int64_t tagId, $outputTypeName$ &reply"
        "$optRecvPayload1$,\n"
        "                                                   ::datasystem::RpcRecvFlags flags) {\n"
        "    return stub_->$methodName$AsyncRead(tagId, reply$optRecvPayload2$, flags);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

void RpcGenerator::ImplementBrpcGenericStubStreamingDef(io::Printer &printer,
                                                        const google::protobuf::MethodDescriptor &method,
                                                        const std::string &indent,
                                                        const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();

    std::string impl =
        "::datasystem::Status $stub$::$methodName$(\n"
        "    const ::datasystem::RpcOptions &opt,\n"
        "    std::unique_ptr<datasystem::ClientWriterReader<$inputTypeName$, $outputTypeName$>> *out) {\n"
        "    return stub_->$methodName$(opt, out);\n"
        "}\n"
        "::datasystem::Status $stub$::$methodName$(\n"
        "    std::unique_ptr<datasystem::ClientWriterReader<$inputTypeName$, $outputTypeName$>> *out) {\n"
        "    return $methodName$(::datasystem::RpcOptions(), out);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

void RpcGenerator::ImplementBrpcGenericStubClientStreamingDef(io::Printer &printer,
                                                              const google::protobuf::MethodDescriptor &method,
                                                              const std::string &indent,
                                                              const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();

    std::string impl =
        "::datasystem::Status $stub$::$methodName$(const ::datasystem::RpcOptions &opt,\n"
        "    std::unique_ptr<datasystem::ClientWriter<$inputTypeName$>> *out) {\n"
        "    return stub_->$methodName$(opt, out);\n"
        "}\n"
        "::datasystem::Status $stub$::$methodName$("
        "std::unique_ptr<datasystem::ClientWriter<$inputTypeName$>> *out) {\n"
        "    return $methodName$(::datasystem::RpcOptions(), out);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

void RpcGenerator::ImplementBrpcGenericStubServerStreamingDef(io::Printer &printer,
                                                              const google::protobuf::MethodDescriptor &method,
                                                              const std::string &indent,
                                                              const std::string &stub)
{
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["stub"] = stub;
    vars["methodName"] = method.name();
    vars["inputTypeName"] = method.input_type()->name();
    vars["outputTypeName"] = method.output_type()->name();
    vars["optSendPayload1"] = HasPayloadSendOption(method)
        ? ", const std::vector<::datasystem::MemView> &payload" : "";
    vars["optSendPayload2"] = HasPayloadSendOption(method) ? ", payload" : "";

    std::string impl =
        "::datasystem::Status $stub$::$methodName$(const ::datasystem::RpcOptions &opt,\n"
        "    std::unique_ptr<datasystem::ClientReader<$outputTypeName$>> *out,\n"
        "    const $inputTypeName$& rq$optSendPayload1$) {\n"
        "    return stub_->$methodName$(opt, out, rq$optSendPayload2$);\n"
        "}\n"
        "::datasystem::Status $stub$::$methodName$("
        "std::unique_ptr<datasystem::ClientReader<$outputTypeName$>> *out,\n"
        "    const $inputTypeName$& rq$optSendPayload1$) {\n"
        "    return $methodName$(::datasystem::RpcOptions(), out, rq$optSendPayload2$);\n"
        "}\n";
    printer.Print(vars, impl.c_str());
}

}  // namespace datasystem
