/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2022. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Description: Service cpp generator.
 */
#include "datasystem/common/rpc/plugin_generator/rpc_generator.h"

namespace datasystem {

void RpcGenerator::CreateServiceCpp(const google::protobuf::FileDescriptor &file,
                                    compiler::GeneratorContext *generatorCtx) const
{
    std::unique_ptr<io::ZeroCopyOutputStream> outputFile(generatorCtx->Open(fileName + ".service.rpc.pb.cc"));
    io::Printer printer(outputFile.get(), '$');

    GenerateServiceCppPrologue(printer, file);
    printer.PrintRaw(namespaceBegin);

    for (auto i = 0; i < file.service_count(); ++i) {
        auto *svc = file.service(i);
        const std::string &svcName = svc->name();
        ImplementZmqCallMethodDef(printer, *svc, PREFIX, svcName);
        ImplementZmqDirectCallMethodDef(printer, *svc, PREFIX, svcName);
    }

    printer.PrintRaw(namespaceEnd);
}

void RpcGenerator::GenerateServiceCppPrologue(io::Printer &printer,
                                              const google::protobuf::FileDescriptor &file) const
{
    std::map<std::string, std::string> vars;
    vars["full_file_name"] = file.name();
    vars["file_name"] = fileName;

    std::string impl =
        "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
        "// source: $full_file_name$\n"
        "#include \"$file_name$.service.rpc.pb.h\"\n";
    printer.Print(vars, impl.c_str());
}


void RpcGenerator::ImplementZmqCallMethodDef(io::Printer &printer, const google::protobuf::ServiceDescriptor &svc,
                                             const std::string &indent, const std::string &svcName)
{
    (void)svc;
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["svcName"] = svcName;
    // brpc dispatches via the generated BrpcAdapter; the zmq CallMethod entry is dead
    // under brpc-only transport. Keep the override defined (RpcServiceBase requires it)
    // but with no zmq dispatch body so generated code does not reference zmq types.
    printer.Print(vars,
        "::datasystem::Status $svcName$::CallMethod(::datasystem::MetaPb meta,\n"
        "                                           std::deque<::datasystem::RpcMessage> &&inMsg, int64_t seqNo) {\n"
        "    (void)meta;\n"
        "    (void)inMsg;\n"
        "    (void)seqNo;\n"
        "    return datasystem::Status::OK();\n"
        "}\n");
}

void RpcGenerator::ImplementZmqDirectCallMethodDef(io::Printer &printer, const google::protobuf::ServiceDescriptor &svc,
                                                   const std::string &indent, const std::string &svcName)
{
    (void)svc;
    (void)indent;
    std::map<std::string, std::string> vars;
    vars["svcName"] = svcName;
    printer.Print(vars,
        "::datasystem::Status $svcName$::DirectCallMethod(::datasystem::MetaPb meta,\n"
        "                                           std::deque<::datasystem::RpcMessage> &&inMsg, int64_t seqNo,\n"
        "                                           std::deque<::datasystem::RpcMessage> &outMsg) {\n"
        "    (void)meta;\n"
        "    (void)inMsg;\n"
        "    (void)seqNo;\n"
        "    (void)outMsg;\n"
        "    return datasystem::Status::OK();\n"
        "}\n");
}
}  // namespace datasystem
