/**
 * Copyright (c) Huawei Technologies Co., Ltd. 2022. All rights reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * Description: Stub cpp generator.
 */
#include "datasystem/common/rpc/plugin_generator/rpc_generator.h"

namespace datasystem {
void RpcGenerator::CreateStubCpp(const google::protobuf::FileDescriptor &file,
                                 compiler::GeneratorContext *generatorCtx) const
{
    std::unique_ptr<io::ZeroCopyOutputStream> outputFile(generatorCtx->Open(fileName + ".stub.rpc.pb.cc"));
    io::Printer printer(outputFile.get(), '$');
    std::map<std::string, std::string> vars;
    vars["fileName"] = fileName;
    vars["fileFullName"] = file.name();
    std::string impl =
        "// Generated by the protocol buffer compiler.  DO NOT EDIT!\n"
        "// source: $fileFullName$\n"
        "#include \"$fileName$.stub.rpc.pb.h\"\n"
        "#include \"datasystem/common/rpc/rpc_client_stream_base_common.h\"\n";
    printer.Print(vars, impl.c_str());
    InstantiateTemplate(printer, file);
}

void RpcGenerator::InstantiateService(io::Printer &printer, const google::protobuf::ServiceDescriptor &svc) const
{
    std::set<std::pair<std::string, std::string>> streamClass;
    std::set<std::string> writerClass;
    std::set<std::string> readerClass;
    std::map<std::string, std::string> vars;
    for (int j = 0; j < svc.method_count(); j++) {
        auto *method = svc.method(j);
        const std::string &inputName = method->input_type()->name();
        const std::string &outputName = method->output_type()->name();
        vars["inputTypeName"] = inputName;
        vars["outputTypeName"] = outputName;
        if (method->client_streaming() && method->server_streaming()) {
            auto ele = std::make_pair(inputName, outputName);
            if (streamClass.count(ele) == 0) {
                printer.Print(vars, "template class ClientWriterReader<$inputTypeName$, $outputTypeName$>;\n");
                streamClass.insert(ele);
            }
        } else if (method->client_streaming()) {
            if (writerClass.count(inputName) == 0) {
                printer.Print(vars, "template class ClientWriter<$inputTypeName$>;\n");
                printer.Print(vars, "template Status ClientWriter<$inputTypeName$>::Read($outputTypeName$ &);\n");
                writerClass.insert(inputName);
            }
        } else if (method->server_streaming()) {
            if (readerClass.count(outputName) == 0) {
                printer.Print(vars, "template class ClientReader<$outputTypeName$>;\n");
                printer.Print(vars,
                              "template Status ClientReader<$outputTypeName$>::Write(const $inputTypeName$ &);\n");
                readerClass.insert(outputName);
            }
        }
    }
}

void RpcGenerator::InstantiateTemplate(io::Printer &printer, const google::protobuf::FileDescriptor &file) const
{
    printer.PrintRaw("namespace datasystem {\n");
    if (!packageName.empty()) {
        printer.PrintRaw(UseNameSpace(packageName));
    }
    for (auto i = 0; i < file.service_count(); ++i) {
        auto *svc = file.service(i);
        InstantiateService(printer, *svc);
    }
    printer.PrintRaw("}\n");
}
}  // namespace datasystem
