option(WITH_TESTS "Enable run datasystem testcases" OFF)
option(BUILD_COVERAGE "Build code for coverage statistics" OFF)
option(FAIL_ON_WARNINGS "Treat compile warnings as errors" ON)
option(ENABLE_PERF "Generate perf point logs" OFF)
option(BUILD_PYTHON_API "Build python api" OFF)
option(BUILD_GO_API "Build go api" OFF)
option(BUILD_JAVA_API "Build java api" OFF)
option(ENABLE_STRIP "Discard symbols from object files" OFF)
option(BUILD_WITH_URMA "Build with urma" OFF)
option(BUILD_TRANSFER_ENGINE "Build transfer_engine as an integrated subproject" ON)

# Hetero device options (requires BUILD_HETERO=ON)
option(BUILD_HETERO_NPU "Build NPU (Ascend) heterogeneous support" ON)
option(BUILD_HETERO_GPU "Build GPU (CUDA) heterogeneous support" OFF)
